### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Xehara** [garbagemule/MobArena#162]
One more suggestion! Sorry >< 
Can you add an ability to view statistics? It'd likely have to be attached to a sql database but, the concept is that you could do a command and bring up stats on a player or the top 10 people on the server. Here's a listing of the information desired:
- Top 10 listing based on times completing all waves.
- Top 10 listing based on times completing using specific class. 
  Summary of all arenas or per arena of the above?
- Player Statistics listing times played, per class, and top wave completion for each class.
  Per arena or summary of all?

**Comment by Trenly** [comment]
I would really love to see all-time stats like Total Kills, Games Played, Waves Played, Highest Wave Reached, etc. I think the stats system has been lacking for some time, and that this should be made a higher priority

**Comment by garbagemule** [comment]
I'm pleased to announce that I've just pushed the (huge) initial commit for a new extension plugin, [MobArenaStats](https://github.com/garbagemule/MobArenaStats). Its sole purpose is to collect, persist and show stats from MobArena sessions, so I consider it a solution to this issue. It's still in a very early stage, and the direction of it is not set in stone. Hopefully, with help from the community, we can turn it into an awesome feature :)

It's not every day you get to close an issue that's over eight years old. @Xehara, if you're still out there, I'm sorry for the delay.
