### ISSUE TITLE
Suggestion: Small Spectator Revamp/Options

### ISSUE THREAD

**Issue by TagCraftMC** [garbagemule/MobArena#213]
Hey Garbage and devs,

I am hoping to have a little revamp of the spectator system or a couple more options added.
1. Option to allow spectators to be invisible to the current players still playing. This will stop people playing thinking that the spectator is also playing.
2. Option to make spectators keep within the bounds of an arena like a player and if they leave the area they will be kicked from the arena like player.
3. Option to allow spectators to fly or give them increased movement/jump.

A example of how these options could be useful is allowing a spectator to spectate with the current players but not interfere with them killing. This would also allow to have more cleaner and immersive arenas as you do not have to "build" a specating area which can look bad or interfere with the arena it's self (example a giant glass platform over a city/town looks bad and can lower light level).

Thanks for your time, Chalkie

**Comment by ct-martin** [comment]
I propose merging parts 1 & 2 into MC's new spectator mode

**Comment by garbagemule** [comment]
Let's close this in favor of #411 to keep with the new template. Great suggestion, and it now seems like there is native support for this kind of thing.
