### ISSUE TITLE
Extra info, classes and waves.

### ISSUE THREAD

**Issue by TagCraftMC** [garbagemule/MobArena#216]
Yes me again Garbage,

This request is to allow us to have a bit more freedom when it comes to the descriptions for waves and classes.

New node for waves.
Wave-Info: This wave is full of scary zombies!
Wave-name: Zombies

New node for classes.
Class-Info: Ahh the Wizard, a class who is adapt at using multiple spells.

New Variable for announcements.yml
%wi = String grabbed from Wave-Info:
%wn = String grabbed from Wave-name: OR the name of the waves already there in the config.
%ci = String grabbed from Wave-Info:

How this could be show/used.
wave-default: Wave &b#%&r! (%wn) is spawning, %wi
wave-default: Wave 1 (Zombies) is spawning, This wave is full of scary zombies!

lobby-class-picked: You have chosen &e%&r as your class, %ci
lobby-class-picked: You have chosen Thewizard as your class, Ahh the Wizard, a class who is adapt at using multiple spells.

**Comment by graywolf336** [comment]
Commenting on this as it would be an extremely useful to have, reminder to myself to see if it's easily implementable.

**Comment by garbagemule** [comment]
@graywolf336 MobArena is undergoing some serious changes these days, so don't spend too much time trying to actually implement it. The waves system is getting an overhaul, and so are the announcements. As always, you're more than welcome on IRC if you want to help crash test some of the changes :)

**Comment by garbagemule** [comment]
Please re-open this if it's still relevant.
