### ISSUE TITLE
PhatLoots Integration

### ISSUE THREAD

**Issue by CapnDuckface** [garbagemule/MobArena#219]
This plugin is improving tenfold and I'm LOVING it, but I know that the chests-meets-metadata issue has been a tad taxing for you.

I've already brought this to the attention of the developer for PhatLoots, however if you could integrate with that plugin to allow for custom boss rewards, supply waves and upgrade waves you could not only make developing a tad easier for yourself long-term, but you'll be able to significantly improve the capabilities of your own plugin.

I've already used PhatLoot chests for custom chests in the MA Arenas I'm creating, but it would be BEAUTIFUL to have them respawn at the end of every game or every few rounds by using your custom hook events.

I know this could be an excellent opportunity and I hope that you both like where I'm going with this. If only I could help with coding (if I knew how or had the time to learn), I'd be willing to look into it for you and attempt a hook/fork of sorts.

Info links below:
PhatLoots Ticket-
http://dev.bukkit.org/bukkit-plugins/phatloots/#c1384

PhatLoots Info & Current Optional Dependancies-
http://dev.bukkit.org/bukkit-plugins/phatloots/#w-supports-nearly-all-bukkit-plugins

**Comment by garbagemule** [comment]
Closing this as PhatLoots is no longer actively developed. Feel free to re-open if still relevant.
