### ISSUE TITLE
Zombies with incredibly high health

### ISSUE THREAD

**Issue by Chakyl** [garbagemule/MobArena#255]
Recently I have pinned down the cause for a major bug with mob arena- Zombies that suddenly gain a bunch of health and are practically invincible. It seems like every time a boss spawns, the bug occurs, which leads me to believe it's a problem with setting the health of a boss.

**Comment by StillSwingin** [comment]
Hi! I have noticed also this bug, I'll provide more information ASAP

**Comment by graywolf336** [comment]
@StillSwingin Able to still provide that information by chance?

**Comment by StillSwingin** [comment]
@graywolf336 i stopped working with mobarena, sorry

**Comment by Sikatsu** [comment]
I also have this issue, but I don't have any zombie boss. I made a ticket on bukkit for you @garbagemule containing more information.

**Comment by ct-martin** [comment]
@Chakyl @StillSwingin @Sikatsu Hello, it's been a while since this issue was commented on, if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
