### ISSUE TITLE
clear-waves-before-next

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#262]
Would it be possible to create a new setting to allow waves to continue to spawn after X amount of time but stop once it reaches a specific number of waves? Example. Continue to spawn waves one after another every 20 seconds up until the 5th wave. Then force players to clear all mobs before waves 6-10 begin. This would allow waves of mobs to pile up if not cleared in time but prevent an overwhelming amount of mobs from accumulating until the end, forcing players to clear instead of running circles.

**Comment by WolfieWaffle** [comment]
Yes please, I have had those issues as well. Or maybe the interval between waves would increase as you go along. When I first start, I have to wait so long for more mobs to spawn, but eventually it seems like the waves are coming at you at light speed. (A bit of an exaggeration, but you get the point).

**Comment by garbagemule** [comment]
How would this look in the config-file?

**Comment by mibby** [comment]
Maybe hook into the ```clear-wave-before-next: true``` setting and create a new one called like ```clear-waves-interval: 1```? With number 1 being default to not conflict with users who previously had clear wave before next set to true for needing every round to be cleared.

The existing ```wave-interval: #``` setting would continue to spawn waves at that interval until it hits the defined clear wave interval cap, until all mobs are killed to begin again.

**Comment by garbagemule** [comment]
Closing this in favor of #449

I know they aren't entirely the same, but a full-fledged per-wave or per-group granularity is a bit too much for the current code base.
