### ISSUE TITLE
[Bug] - Exploding sheep are causing block damage inside the arena.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#265]
MobArena 0.96.9.1

@garbagemule Exploding sheep swarm waves are causing block damage inside the arena. Grass blocks to be specific were being destroyed, creating holes.

**Comment by garbagemule** [comment]
http://dev.bukkit.org/bukkit-plugins/mobarena/tickets/1414-exploding-sheep-blowing-holes-in-arenas/

**Comment by mibby** [comment]
:(
