### ISSUE TITLE
Add title messages for waves

### ISSUE THREAD

**Issue by bendison** [garbagemule/MobArena#272]
[revised by garbagemule]

I was wondering if it was possible to add the sending of wave numbers as titles as well as a title upon entering the arena? Maybe for the entrance message have the title as "Arena Name" subtitle "Description of arena or a good luck message". 

---

[original issue]
> I was wondering if it was possible to add the sending of wave numbers as titles as well as a title upon entering the arena? Maybe for the entrance message have the title as "Arena Name" subtitle "Description of arena or a good luck message". 
> 
> I was also wondering if it would be possible to add the ability to edit the [MobArena] prefix in the announcements file.
> 
> Finally having the ability to set the lore on items for classes and their items would be a really nice feature.
> 
> Thanks for reading to my suggestions!
>

**Comment by garbagemule** [comment]
This is currently not supported, and it will take a bit of a rework of the current announcements system to implement. However, the announcements system as a whole is due for an overhaul, and it is on the drawing board for the rewrite :)

**Comment by DiscoveriesMC** [comment]
Thanks for letting me know! In general I think that more customization of the plugin would be really nice for those servers who want to have that extra twist on this classic plugin. Thanks for your hard work! :)

**Comment by garbagemule** [comment]
This issue is about using titles to display wave numbers and other fancy stuff. It's a brilliant idea and could reduce some of the chat spam.
