### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Synida** [garbagemule/MobArena#273]
Hello!
1. I've an arena, where I'm using first-wave-delay. If everyone is leaving this arena before the first wave then in the next turn, the first-wave-delay didn't counting from zero, it will continue the previous turn's delay.
2. If everyone is leaving the arena becouse connection error, then the arena's soft-restore module is not working.
3. If everyone is dying, before killing the first boss(an enderdragon), then the dragon will remain in the arena, the another mobs will be removed. Bonus: I'm tried to fix it with command block(/butcher 50): when the new turn's warriors are in the lobby, they can press a button, but nothing happens, becouse the button doesn't send signal.

Sorry for my english, if somesthing is not clear, I'll explain it. 
- thanks for helping.

**Comment by ct-martin** [comment]
Hello, it's been a while since this issue was commented on, if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
