### ISSUE TITLE
[BUG] Zombies can't breaking doors in the arena

### ISSUE THREAD

**Issue by Synida** [garbagemule/MobArena#274]
Hi!
Outside one of my arenas, the zombies can breaking doors, but inside it's not working. I'm using the v0.97.1 version. It doesn't cout, what im doing in the config file, it's not working.  I think, people can call this as a "feature", but by default the zombies breaking doors on the hard difficult, and I also have some excited arena ideas.

**Comment by ct-martin** [comment]
@Synida Hello, it's been a while since this issue was commented on, if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
