### ISSUE TITLE
Null Message

### ISSUE THREAD

**Issue by Azfaloth** [garbagemule/MobArena#278]
I have mobarena on a server that also has Mythic Mobs. From Mythic mob version 2.1.5 onwards, whenever a player dies from the mobarena, everyone on the server gets the usual "mob arena finished, type /ma j <name> to join a new game"

After this there is also a white "null" that appears in chat for everyone on the server.

Is there any way I can fix this?

**Comment by Nanoripper** [comment]
Same issue with the latest version.

**Comment by garbagemule** [comment]
I don't think the null is from MobArena. All of MobArena's messages have the [MobArena] prefix.

Can you try to reproduce this on a fresh environment with no other plugins than MobArena?

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
