### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by StormyBluey** [garbagemule/MobArena#279]
I need help 
I don't know if this is a thing or not but can somewon please explain the  abilitys thing to me 
to add to kits/classes I am very confused but I can learn if somewon can explain it to me or give me a example because I what to add a fireball like the boss's have but I don't know how to If somewon ansters my question that well be lovely

**Comment by Pyeroh** [comment]
First, you should correct your english. I'm french, but I try to write correctly every time I'm answering someone, on Github or everywhere else. I'm not trying to be mean, but I barely understood what you meant...
Next, abilities for a class in MobArena don't exist. However, you can add a plugin which add some sort of magic and spells, and add the permission linked to a spell in the class' permissions declaration.
