### ISSUE TITLE
[ArenaHelp] Potions can't be used

### ISSUE THREAD

**Issue by iAerosoft** [garbagemule/MobArena#281]
For some reason, potions don't work in the arena. The arena isn't in a world guard region either.

**Comment by iAerosoft** [comment]
I have further researched that there was a conflicting plugin causing this problem

**Comment by garbagemule** [comment]
Glad you figured it out!

Mind sharing which plugin caused the problem in case other people have the same problem?

**Comment by iAerosoft** [comment]
Yea sure! The Heroes RPG Plugin (Has skills and classes) has some skills that require you to be able to use potions, so if you have this plugin, make sure to give all players the skill or to remove so you can use potions in MobArena! Hope that helped!
