### ISSUE TITLE
Missing commits on repo up to published version 0.97.1

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#285]
Repo stops at 0.96.9 while latest published version on bukkit is 0.97.1. Shouldn't the commits be pushed to the repo?

**Comment by garbagemule** [comment]
Yep! They'll be pushed at some point. I had some sort of plan that involved not pushing the changes, but I forget what it was. Probably world domination or something like that.

**Comment by mibby** [comment]
Thanks. :)
