### ISSUE TITLE
Update Class Chests to support extra off-hand inventory slot in 1.9.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#287]
https://github.com/garbagemule/MobArena/wiki/Class-Chests

Need to update the global class chest to support the off-hand inventory slot. Assuming Class Chests are now the only way to provide potions to a class since potion IDs were removed. :)

Also seems adding potions to an upgrade wave is impossible now for the same reason - no IDs to fallback on.

**Comment by mibby** [comment]
@garbagemule In addition, the armor in the last 4 slots do not seem to copy on the user when they pick the class. Doesn't appear anywhere. I'm assuming it broke with 1.9's new inventory, no errors at all.

**Comment by mibby** [comment]
Armor issue fixed here.
https://github.com/garbagemule/MobArena/pull/288

**Comment by garbagemule** [comment]
Fifth last slot will be equipped in the off-hand slot.
