### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by browe454** [garbagemule/MobArena#290]
I am running a 1.9 server and when a player tries to start the mob arena it allows them to select a kit but once they ready up and join after a few seconds it kicks them and the server crashes? Do you have any idea what might be causing this? I can provide server logs if needed

**Comment by browe454** [comment]
@garbagemule Do you know what might be causing this issue?

**Comment by garbagemule** [comment]
Sorry for the late response - yeah, fork over the logs and I'll take a peek.

I prefer to keep the github issue tracker reserved for actual source code related stuff that other developers can chime in on, and not just random crashes or bugs. In the future, please use the tickets on dev.bukkit.org for stuff like this :)
