### ISSUE TITLE
Double output occurs when right clicking with region setup tools.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#299]
MobArena 0.97.2 (Custom compiled your secret build)
MC 1.9.4
Paper dev 749

Double output / event occurs when right clicking with the region setup tools in 1.9. It sets points twice and when toggling between warps, it skips over 1 since it occurs twice.

**Comment by garbagemule** [comment]
Hah, that's a pretty odd thing. What's Paper?

**Comment by mibby** [comment]
The double output occurs because of the offhand added in 1.9. I assume you are listening for any right click instead of specifying a specific hand / item? WorldGuard recently pushed a fix for it here. 
https://github.com/sk89q/WorldGuard/commit/15a9c50ea4c1fbf2c3c0b096d2c691527f01320b

Paper is a fork of spigot with additional fixes and performance tweaks from those who originally and still do contribute upstream to spigot.
https://paper.readthedocs.io/en/paper-1.9/

**Comment by garbagemule** [comment]
Thanks for the link and the explanation!

I think I'm gonna look into this as soon as my carpal tunnel calms back down again. Puny wrists! :(

**Comment by mibby** [comment]
Anytime. :)

**Comment by Kayepur** [comment]
Any news on this issue? I have it when I am trying to set warp points still. I have MA v 0.97.1, MC 1.9.4. Please advise. Thanks!

**Comment by mibby** [comment]
Agreed. An update would be great. :)

**Comment by garbagemule** [comment]
My RSI is still very much alive and kicking my ass, so no update, sorry. I've barely touched a keyboard the past 3 months, and whenever I do, my elbows, forearms, wrists, and hands all flare up and start hurting.

@mibby Can you hit me up on IRC today between 5 PM and 8 PM CET?

**Comment by mibby** [comment]
@garbagemule I hopped on the IRC but you didn't seem to be around. What's up?

**Comment by garbagemule** [comment]
@mibby Yeah, it was 1 AM and I had gone to bed, haha. I'll be around from 5 PM till around midnight today if you have time :)

**Comment by mibby** [comment]
Oops. Misread timezone. :P
