### ISSUE TITLE
Arena are not covered by any spawnpoints

### ISSUE THREAD

**Issue by rErEaT** [garbagemule/MobArena#300]
31.05 10:16:21 [Server] WARN [MobArena] The following locations in arena 'MobArena' are not covered by any spawnpoints:(1044,9,1182) (1043,9,1181) 

How can i fix this?

**Comment by garbagemule** [comment]
Add a spawnpoint on or close to that location.

**Comment by rErEaT** [comment]
how can i do that?

**Comment by garbagemule** [comment]
Find the locations in your arena, then use the spawnpoint command or the spawnpoint tool in Setup Mode :)
