### ISSUE TITLE
Only get these when someone joins a game

### ISSUE THREAD

**Issue by MrsKliper** [garbagemule/MobArena#305]
Mobarena works I just get these in console every time someone starts a game, I have redid setting up the arena twice so far, any ideas what is causing this?

WARN The following locations in arena 'FightClub' are not covered by any spawnpoints:(-794,64,10026) 
13.06 10:34:46 [Server] WARN The following locations in arena 'FightClub' are not covered by any spawnpoints:(-800,64,10028) 
13.06 10:34:30 [Server] WARN The following locations in arena 'FightClub' are not covered by any spawnpoints:(-796,64,10023) 
13.06 10:34:15 [Server] WARN The following locations in arena 'FightClub' are not covered by any spawnpoints:(-802,64,10034)

**Comment by aycgit** [comment]
This error looks like there isnt a set spawnpoint, how many spawnpoints do u have in your arena fightclub

**Comment by garbagemule** [comment]
This warning is printed when MobArena is trying to spawn monsters and no players are within 15 blocks of a spawnpoint. Create more spawnpoints to fix.
