### ISSUE TITLE
/ma class (classname) not working

### ISSUE THREAD

**Issue by Razkel** [garbagemule/MobArena#306]
Spigot Version: 1.9.4-R0-1-SNAPSHOT
Plugin Version: 0.97.1

So I am setting up my first arena and I am making the classes. I used /ma classchest Swordsman on a chest that contained an enchanted sword and set of armor and 2 potions of healing, but when I use /ma class Swordsman nothing happens. 

All I got from the console was **[00:34:11 INFO]: Razkel issued server command: /ma class Swordsman**  and nothing else regarding the plugin.

**Comment by aycgit** [comment]
I dont know if it still is but its true that classchests were broken

**Comment by aycgit** [comment]
U should look in the config if the class exists

**Comment by MarkehMe** [comment]
This usually happens if the class does not exist (the plugin tends to be silent on error). I've been working on fixing this in [my fork](https://github.com/PlanetCraft/MobArena).

**Comment by slipcor** [comment]
Yeah you need to have the class defined AS class, this does not happen by using the command.

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
