### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TheMunkeh** [garbagemule/MobArena#308]
http://pastebin.com/raw/BP41KVPN

Some where down the line I messed up, can someone help me

**Comment by AwesomeMan2812** [comment]
Well, your spacing isn't that good, I would recommend fixing that before I check anything else.

**Comment by slipcor** [comment]
Yes, you definitely need to fix your spacing, YML is really bad about that but there is nothing MobArena can fix about this, you need to get it straight!

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
