### ISSUE TITLE
Multiple commands to join error.

### ISSUE THREAD

**Issue by CShayne** [garbagemule/MobArena#309]
I have factions and I implemented mob arena in it and I made it so /ma join and /ma spectate have a cooldown of 5 seconds so no 1 can teleport away without the cooldown, but with this plugin there are multiple commands u can do /ma joinnnnnnn, /ma joinwdwijwjdwidjw, /ma specccwdwdwwwd and it will count as /ma join and /ma spec and it wont have the cooldowns as it is a different command but not really and it wont have the cooldown that I added on the /ma join and /ma spec how do I fix this?

**Comment by slipcor** [comment]
I guess you would have to make it support the wildcard system that MobArena uses in the argument?

If that does not work, would it not be okay to restrict the WHOLE command /ma to a 5 second cooldown?

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
