### ISSUE TITLE
Can't get into setup mode.

### ISSUE THREAD

**Issue by TheaPMC** [garbagemule/MobArena#311]
I'm running a bungee/spigot server, with MobArena on a 1.9.2 seperate server at the moment while I try to get it running. I have tried v0.97.1 as well as the 1.9 version from here:  https://dev.bukkit.org/bukkit-plugins/mobarena/forum/116701-how-to-update-mob-arena-to-1-9/#p6
There are no errors and I have removed all plugins from the server.  When I go into /ma setup it takes me in just fine and I am able to set points but none of the other commands will work (for example I cannot expand the region) When I attempt to exectute any commands in the chat line it just posts as chat, (when I execute them legacy style it just does nothing at all) in other words I am not entering the isolated conversation mode?  I haven't altered anything in the config file at all other than to add the arena and delete the default which I did using in game commands as per the wiki.

arenas:
  Phoenix:
    settings:
      world: world
      enabled: false
      protect: true
      entry-fee: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      hellhounds: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      auto-respawn: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      first-wave-delay: 5
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: true
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true

**Comment by AwesomeMan2812** [comment]
Ok, well setup mode is its own thing. In setup mode, all you do is just setup the points and stuff for an area. It purposely makes it so you can't do anything else except for saying certain things in chat. For Example: I'm done finishing setting up my area, but how do i leave this mode? Answer: Just type "done" (without the quotation marks) in chat, and BOOM your done! If you just type "?" (without the quotation marks) while your in setup mode, it should tell you what you can do while in setup mode. Otherwise expanding a region while in setup mode just basically isn't possible.

**Comment by TheaPMC** [comment]
Yes, I understand that; let me try to be a little more specific.  :)  When I type "/ma setup <nameofmyarena>" it seems to work, I get the tools in my inventory, I can fly etc. What does not work is any typed commands. What happens, for example, is I type ? and it just outputs ? to chat. Nothing happens and the other players on the server can see it.  So while I can set P1 and P2 I can't get any further than that; can't expand the region or do anything that requires typed commands.

**Comment by AwesomeMan2812** [comment]
Thats weird, yeah got no idea how to fix that. Well, hope someone can find out something for ya. Or I can  just contact ya if I find out a fix.

**Comment by TheaPMC** [comment]
I figured it out. It's definitely a bungeecord issue. I was able to set bungeecord to false in the spigot.yml, direct connect in to the server and set it up from there.

**Comment by AwesomeMan2812** [comment]
Good to know! Hope everything goes well for your mobarena game after this!

**Comment by garbagemule** [comment]
Closing this as issue was resolved. If there's more trouble with Bungee, please create a new Bungee-specific issue.
