### ISSUE TITLE
Potion errors

### ISSUE THREAD

**Issue by AwesomeMan2812** [garbagemule/MobArena#312]
So this isn't a code error but an ingame error, When you add kits to the game with potions, they just turn into water bottles when you pick a class. Its also any kind of potion, like lingering or splash that this happens as well. I've found a way to overcome this, with using class chests none of this happens, however what the main problem is for me is I have a class just like chemist but using lingering potion instead. What I wanted to do was on an upgrade wave give them a lingering potion of healing, but just like when you try adding potions to kits without using class chests, it just gives you a missing texture lingering water bottle. Please help if you can, using the latest version of MobArena (v0.97.1) on a 1.9 server.
`up1:`
          `type: upgrade`
          `wave: 11`
          `upgrades:`
           `Bowman:`
              `items: bow 48:1;49:1, arrow:32`
            `Wolfmaster:`
              `items: wooden_sword 17:3;18:2`
              `armor: chain_leggings`
            `Scientist:`
              `items: lingering_potion:16385:1`
              `armor: iron_boots`
            `Bodyguard:`
              `items: 373:16385:1`
              `armor: diamond_boots`
            `Ironbomber:`
              `items: tnt:2`
              `armor: diamond_boots 3:2`
          `give-all-items: true`

**Comment by slipcor** [comment]
this is fixed in either latest MobArena or along the line in a Spigot server version - it should work! (it did for me testing today)

**Comment by AwesomeMan2812** [comment]
I saw what he said on bukkit about this problem, happy that hes worked on it! I'll try out the new version to see if its fixed. Once checked, I will close this issue.
