### ISSUE TITLE
Error in restoring Player inventory on /ma leave

### ISSUE THREAD

**Issue by Firestar311** [garbagemule/MobArena#315]
Hello, I am running Spigot 1.10.2 and have MobArena setup. Whenever someone dies, and tries to do /ma leave, an error in the console is thrown about not being able to restore the inventory. Pastebins are below.
Whenever the /ma force end <arena> command is run, same error. Below is the error copy and pasted from the log file, as well as the config. This error pops up when you do /ma leave, the force stop and disconnecting from the server. 

[Log file error](http://pastebin.com/wE58NVdX)
[Config.yml](http://pastebin.com/vcCCmAfz)

**Comment by slipcor** [comment]
```
    rewards:
      waves:
        every:
          '2': 22261
          '5': 352:4, 1:5, 354:1, 357:2, 115:1, 260:5, 350:8, 318:4
        after:
          '9': 267:1, 292:1, 256:1, 257:1, 258:1, 276:1, 278:1, 279:1
          '13': 306:1, 307:1, 308:1, 309:1, 310:1, 311:1, 312:1, 313:1
          '19': 322:8, 264:8, 373:8233:8, 302:1, 303:1, 304:1, 305:1
          '24': 276:1 17:1;18:2;20:1, 311:1 1:3, 310:1 3:4
          '33': 23080```

every->2 and after->33 have to be string entries (for the other ones it is okay because there are so many in there)

So you have to surround the values with single quotes:

```
    rewards:
      waves:
        every:
          '2': '22261'
          '5': 352:4, 1:5, 354:1, 357:2, 115:1, 260:5, 350:8, 318:4
        after:
          '9': 267:1, 292:1, 256:1, 257:1, 258:1, 276:1, 278:1, 279:1
          '13': 306:1, 307:1, 308:1, 309:1, 310:1, 311:1, 312:1, 313:1
          '19': 322:8, 264:8, 373:8233:8, 302:1, 303:1, 304:1, 305:1
          '24': 276:1 17:1;18:2;20:1, 311:1 1:3, 310:1 3:4
          '33': '23080'```

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
