### ISSUE TITLE
Your system asked me to make you this ticket

### ISSUE THREAD

**Issue by TheChampTF** [garbagemule/MobArena#317]
02.10 00:47:31 [Server] ERROR http://dev.bukkit.org/bukkit-plugins/mobarena/tickets/ 02.10 00:47:31 [Server] ERROR Please make a ticket and inform me about this at: 02.10 00:47:31 [Server] ERROR AUTO START TIMER WAS NOT STOPPED!

**Comment by slipcor** [comment]
Yeah but there should have been an error in the server.log at that time, right?

If nothing bad happened after that, maybe it was just a hickup?
