### ISSUE TITLE
Leaving so soon. What to do?

### ISSUE THREAD

**Issue by studentCRAFT** [garbagemule/MobArena#321]
Mob Arena is not working
I write /ma join, I choose a class, run the arena and writes "Leaving so soon?"
What to do?
config.yml: http://pastebin.com/xyshprU0

**Comment by slipcor** [comment]
The config looks fine. Can you check that no plugin is preventing the teleport?

If you did that (no message about the teleport being blocked) I would offer to send you a special build that will print to you the location you were at when this happens, so we know if it is a MobArena issue in the sense that MobArena does not consider your place valid (whereas it should be, based on the config I see) - or if it is an issue with GETTING you there in time.

One more thing, could it be that you are very far away from the arena when joining, like tens of thousands of blocks?

**Comment by garbagemule** [comment]
Closing this as it's now very old and unanswered. Reopen if problem persists.
