### ISSUE TITLE
NoSuchFieldError with MobArena v0.97.3

### ISSUE THREAD

**Issue by AwesomeMan2812** [garbagemule/MobArena#333]
Downloaded the new release today of the MobArena plugin and tried it out. Next thing I see is that the plugin tells me to look at the logs because there is an error. I check and I find that it is giving me this error: [Error Link](http://pastebin.com/MmPM3SRQ).

The version of Minecraft I'm running is 1_9_R1 (1.9), don't know if that's the problem but I just wanted to see if the potion error I said in an earlier issue was fixed.

**Comment by garbagemule** [comment]
Yep, that is a problem. v0.97.3 requires Minecraft 1.11.
