### ISSUE TITLE
[Feature] Command Rewards & Optional Delay after clear-wave-before-next

### ISSUE THREAD

**Issue by HeadlessJoey** [garbagemule/MobArena#334]
Hi, I was told to write down some suggestions here to improve the plugin.

First, when using the "clear-wave-before-next: true" it would be good to add an option for a timer after each wave. So waves don't instantly start after you killed all monsters but so you can have a little timer after each wave to heal up.

Second and last, an option to queue up commands as rewards. So instead of only being able to give items and money as rewards you can queue up a command. Then this command would trigger when the player leaves (just like when giving the items). Personally I would use this to make a command happen to give the player a special item from another plugin (simply put they could get a "voting key"). 
Ofcourse the commands would need a tag like <player> which would automatically fill with the player's name who is getting the reward.

**Comment by Alphexon** [comment]
I can definitely vouch for the command rewards. That would open up many possibilities for server admins.

**Comment by SaitDev** [comment]
+1
The command reward is something I really like to improve a multi floor mobarena. Finish each floor run a command that give permission for next floor.

**Comment by garbagemule** [comment]
First has a new single-issue duplicate here: #449 

Second is already implemented.
