### ISSUE TITLE
ClassChest Armor not Equipping

### ISSUE THREAD

**Issue by HeadlessJoey** [garbagemule/MobArena#335]
Hi,

I tried everything to get the ClassChests to equip armor automatically but nothing worked.
Using the latest Spigot 1.11.2, latest MA 0.97.3. Happened both on a fresh server and one with plugins.
So I make the arena, lobby, etc..
Then I enable ClassChest option in the config.
Then under my sign in the Lobby I put the chest with the items: http://prnt.sc/dolr42
And then when the player clicks the sign it only gives him the items at the top of the chest but it won't equip the armor.

I tried everything:
Putting the chest inside the Lobby region, outside, using /ma classchest Knight and having the chest inside or outside the lobby regions.
Fresh server, old config (where I edited waves, rewards etc..), new config.
Everytime it gives the sword and potion but it doesn't equip the armor (the armor isn't in the player's inventory either).

**Comment by garbagemule** [comment]
I think I've already fixed this previously in a dev build, but it never made it to github. I think slipcor has a pull request ready with the changes, so I might be able to push a new build with the fix soonish. Either on Dec 29 or primo January.

**Comment by slipcor** [comment]
Here you go, it should work now!

https://dev.bukkit.org/projects/mobarena/files

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
