### ISSUE TITLE
Class Chests not saving to config

### ISSUE THREAD

**Issue by Alphexon** [garbagemule/MobArena#337]
After setting a class chest in-game and doing "/ma config save", it still does not save the data to the config. Reloading the config breaks the class chest links. There are no errors in the console.

Using MobArena 0.97.4.

**Comment by slipcor** [comment]
Hmm. First off, setting a class chest will never have the chest's value in the config, rather there should be a new node under the classes armor/item definition looking like

classchest: x,y,z

So that is the only thing that should be added. About the reloading, I will try to reproduce this error. Do you reload with /reload then or how do you reload the config?

**Comment by Alphexon** [comment]
It doesn't save the class chest coordinates. I'm reloading the config with the "/ma config reload" command.

**Comment by Alphexon** [comment]
It does save on server restart, but not when using the save command.

**Comment by garbagemule** [comment]
There is almost never a reason to use /ma config save, and you should only ever use /ma config reload when you have changed the file on disk manually. When you type `/ma classchest <class>`, the `classchest` node is set in the config-file for the given class, the config is saved, the "Class chest updated for class <class>" message is sent to you, and all classes are reloaded (i.e., the save and reload happens automatically): https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/commands/setup/ClassChestCommand.java#L56-L59

Does `<class>` actually exist in the the config-file? Do you see the "Class chest updated for class <class>" message?

You should as a bare minimum see some sort of message on screen or in the server log - anything else is virtually impossible.

**Comment by Alphexon** [comment]
It gives me the message that says "Class chest updated for class". The class does exist in the file. It's just not saving "classchest: <coords>" to the file after running the "/ma classchest" command.

**Comment by garbagemule** [comment]
Alright, thanks. We'll take a peek soon :)

**Comment by slipcor** [comment]
So here is what I did and I had the config ready and it was updating as follows:

Before Server startup:
- no classchest entry
After classchest command:
- classchest entry
After config reload command:
- classchest entry still there
After stopping the server
- classchest entry still there

I will correspond with the mule if he has ideas but I have none, it is working fine on my windows machine. Are you maybe using a program (editing or FTP or both) that might ignore changes and override your local version?

**Comment by slipcor** [comment]
are you available to join the IRC this thursday, this time, so 10pm CET ?

#mobarena on irc.esper.net

We would like to look into this issue together with you

**Comment by Alphexon** [comment]
I'm starting to think it's the FTP. Oddly enough, it shouldn't have been modifying the file like it was. I've never experienced the issue with any other plugin, but I've never done much editing with plugins that are configurable in-game. I have tested the reload command without connecting to the FTP server, and it seems to be working. My apologies for wasting your time.

**Comment by slipcor** [comment]
It's ok. Most important thing is that it works!

**Comment by garbagemule** [comment]
@Alphexon You learned something about FTP and open files, and we got to revisit some class chest mechanics. It was a waste of no one's time :)
