### ISSUE TITLE
"Flagged as ready" message firing twice

### ISSUE THREAD

**Issue by Alphexon** [garbagemule/MobArena#340]
When right-clicking the iron block to flag yourself as ready, the message, "You have been flagged as ready" is being sent to the player twice. This likely due to the PlayerInteractEvent firing for both the main and off hand.

Spigot 1.11.2, Mob Arena 0.97.4.

**Comment by garbagemule** [comment]
What a beautifully concise and informative bug report, thanks! 

I think you're right. We recently fixed a similar issue with Setup Mode. To be sure, it only happens when right-clicking, and not when left-clicking, correct?

**Comment by Alphexon** [comment]
Yes. It only happens when right-clicking.

**Comment by slipcor** [comment]
Oh, I thought I fixed all instances of this happening in https://github.com/garbagemule/MobArena/commit/60a173d447dcee94bc03b65e549eb6271198dc6b

Should be an easy fix though :D
