### ISSUE TITLE
Splash and lingering potions show as checkered cubes

### ISSUE THREAD

**Issue by ShepherdJerred** [garbagemule/MobArena#343]
As of 0.95.5 with Spigot 1.11.2, splash and lingering potions don't properly work with classes.

Here's the class configuration
`splash_potion:8229:16, splash_potion:8226:4, splash_potion:8233:2, splash_potion:8202:8`

And in the end a checkered cube is given instead of the proper item [Image](http://i.imgur.com/4mZNamU.png)

No errors in the console either.

**Comment by slipcor** [comment]
Alright, so I am currently working on fixing this. Lingering potions will be an issue until some rewriting has been done. The numerical data value will never properly support lingering potions. The last possible addition was "splash" which actually will work if you:

* replace splash_potion with potion
* add 16384 to the data value

But lingering potions would need a value of 32768 to add, that is not possible :/

We will think about how to solve this!
