### ISSUE TITLE
Prevent Mobs from Picking Up Loot

### ISSUE THREAD

**Issue by Alphexon** [garbagemule/MobArena#344]
Sometimes mobs spawn with canPickupLoot set to true. This can be frustrating because mobs may steal drops from broken blocks (if you have a class with blocks) or dropped items if sharing is enabled. Once they pick an item up, it's gone forever. 

My suggestion is to either prevent mobs from picking up loot by setting canPickupLoot to false when they spawn, or make them drop whatever they picked up when they die.

**Comment by garbagemule** [comment]
Hahahaha, I had no idea this was a thing xD

Thanks for reporting this. I'll take a look soon.
