### ISSUE TITLE
(Tiered rewards) Non-accumulating or "upgrading" rewards 

### ISSUE THREAD

**Issue by MunkeyMadness** [garbagemule/MobArena#346]
I have just a few questions.
Upon rewarding items, is it possible to run a command from inside the console, for example. round 30 achieved, it runs /give spawner crate. to the victor.  converting commands through another plugin

2: can you set a reward to that specific wave only. They die before round 50 they only get round 45's reward and not round 40, 30, 20 etc.

**Comment by garbagemule** [comment]
1: Not currently, but it's on the board. 

2: Use the 'after' branch.

**Comment by MunkeyMadness** [comment]
Can you make it where players join with their own gear and it breaks. Everything in the classes are unbreakable. 
I want to create a arena where players bring their own gear and they have to fight in the arena.

**Comment by garbagemule** [comment]
Just to sort of recap this: the idea here is to define a sort of tiered reward system where the next level of rewards replaces the ones in the current level, effectively making it possible to "upgrade" rewards along the way without having to grant every single tier. As an example (using the "grouping" functionality proposed in #386):

    rewards:
      tiered:
        '4': all(leather_helmet, leather_chestplate, leather_leggings, leather_boots)
        '12': all(iron_helmet, iron_chestplate, iron_leggings, iron_boots)
        '30': all(diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots)

Here, beating wave 4 rewards a set of leather armor, but beating wave 12 replaces that set with an iron armor set, and if you beat wave 30, you get diamond armor instead. That is, the reward gets better the longer you go, but the rewards don't "add up" along the way.

I think having a `tiered` or `tiers` section would actually work pretty well, providing this extra functionality without interfering with or depending on the existing rewards sections. Perhaps the Things API could be expanded with a TieredThing that supports a type of `next()` operation, wrapping sets of Things for each level.

**Comment by Porkason** [comment]
> Just to sort of recap this: the idea here is to define a sort of tiered reward system where the next level of rewards replaces the ones in the current level, effectively making it possible to "upgrade" rewards along the way without having to grant every single tier. As an example (using the "grouping" functionality proposed in #386):
> 
> ```
> rewards:
>   tiered:
>     '4': all(leather_helmet, leather_chestplate, leather_leggings, leather_boots)
>     '12': all(iron_helmet, iron_chestplate, iron_leggings, iron_boots)
>     '30': all(diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots)
> ```
> 
> Here, beating wave 4 rewards a set of leather armor, but beating wave 12 replaces that set with an iron armor set, and if you beat wave 30, you get diamond armor instead. That is, the reward gets better the longer you go, but the rewards don't "add up" along the way.
> 
> I think having a `tiered` or `tiers` section would actually work pretty well, providing this extra functionality without interfering with or depending on the existing rewards sections. Perhaps the Things API could be expanded with a TieredThing that supports a type of `next()` operation, wrapping sets of Things for each level.

This seems great and would really help when you give players a command similar to vault or tokenenchant. So you don't get tons of messages with new balances and token balances. +1 for this idea.
