### ISSUE TITLE
Lingering Potions Bug

### ISSUE THREAD

**Issue by BeksOmega** [garbagemule/MobArena#350]
I have lingering potions set up in the class chest of a mage class. But when players join the arena and try to use them they just act like splash potions. Pvp-enabled is not effecting it because this has happened with it on and off. If you know of anywhere I could look to try and fix this I would super appreciate it! ty!

**Comment by slipcor** [comment]
Please double check that you properly set up the class chest. What MA does is literally copy the item, so if this does not work (and you did not make a mistake) this is a bug in Spigot.

Can you www.pastebin.com your config so we can take a look at your classchest settings?

**Comment by slipcor** [comment]
I just verified that it works on the latest MA build available, added a lingering night vision potion to a chest and selected the corresponding class. It works :)

**Comment by BeksOmega** [comment]
Sorry for the slow response!

So we've done a bit more testing and lingering potions seem to work for me (Admin Deopped) but no one else. 

config: http://pastebin.com/30JcDknz

**Comment by slipcor** [comment]
You need to redo your class chests, your class definitions are empty. There needs to be something similar to

```
classes:
    ClassName:
        classchest: x,y,z,0.0,0.0,world
```

So please redo the /ma classchest [classname] :)

**Comment by BeksOmega** [comment]
Ok figured out the issue!

Turned out it wasn't an issue with the classchests but with a potion-splash WG flag. Ty for the help! and sorry to waste your time.

Ty again for the work you do with the plugin. Our players love it and they're excited to play with it more.
