### ISSUE TITLE
[Feature request] Shulkers

### ISSUE THREAD

**Issue by Sikatsu** [garbagemule/MobArena#353]
It would be nice if there is an option to disable shulker teleporting, as they keep teleporting out of the arena.

**Comment by garbagemule** [comment]
This sounds a bit strange. If shulkers warping around fires EntityTeleportEvents, the warps should be cancelled if the warp happens either from or to the arena region. Without an event to cancel, there isn't really much that can be done about it aside from forcefully moving the shulker back into the arena region somehow (super icky).

**Comment by slipcor** [comment]
welp... seems shulkers - or at least the shulkers MA creates - do not trigger a teleport event

**Comment by slipcor** [comment]
I made a ticket on spigot. Their special way of teleporting does not trigger a teleport event. I showed them the place in the code where to fix it, let's see when they come around to fix it ^^

**Comment by Sikatsu** [comment]
It seems they added the EntityTeleportEvent in their latest commit ^^

**Comment by slipcor** [comment]
yes, I verified that it works on latest spigot version :)

**Comment by garbagemule** [comment]
I guess we can close this then :)
