### ISSUE TITLE
please, Don't block bed explosions!

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#356]
If I install MobArena on my server, beds after explode (right click on it) will not be able to damage & drop any blocks in Nether or in The End, and I can't change that..

**Comment by garbagemule** [comment]
Is there a particular reason you want exploding beds in your arenas? Can't you just use TNT?

**Comment by molor** [comment]
No, the problem is not only in the arena.
At any time, not even during game in arena, the bed does not destroy blocks in Nether or The End..

**Comment by garbagemule** [comment]
Ahh, so you're saying that when MobArena is installed, all bed explosions on the server, regardless of them happening in an arena or not, are affected?

**Comment by molor** [comment]
@garbagemule, yes! Try to install MobArena only and explode bed for example, in the Nether. Its explosion will not damage blocks.
It makes me sad..

**Comment by garbagemule** [comment]
Alright, I see why. There's an arguably unfortunate design choice in the Bukkit API that makes this whole thing a little tedious to get around.

Can you try this dev build and let me know if it works for you or not?
https://dl.dropboxusercontent.com/u/11723967/ma/MobArena.jar

**Comment by molor** [comment]
@garbagemule, this build works, bed explodes

**Comment by garbagemule** [comment]
Thanks, the fix is included in the upcoming v0.97.5.
