### ISSUE TITLE
Items cannot be placed in beacons

### ISSUE THREAD

**Issue by Alphexon** [garbagemule/MobArena#357]
Even if "share-items-in-arena" is set to true and the arena is in edit mode, you can't place items in beacons to activate them. I'm getting the message, "Sharing is not allowed at this time!" Placing items in other containers such as chests works fine.

Spigot 1.11.2, MobArena 0.97.4.

Edit: Sometimes there's a fluke where I can actually put items into the beacon, but then it will stop working again. I can't figure out the difference. I haven't touched the FTP files or anything; everything's been in-game.

**Comment by garbagemule** [comment]
I can't reproduce this at all. I'm always able to place the items into the beacon (but only valid items, e.g. a diamond or an iron ingot).

Is this still happening on v0.97.5?

**Comment by garbagemule** [comment]
I assume this is no longer an issue. Reopen if it is.
