### ISSUE TITLE
Wolves on arena attacks Killer Bunnies instead of the player.

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#364]
Hello. The problem is written in the issue title.

**Comment by garbagemule** [comment]
So if you have both killer bunnies and wolves in a wave, the wolves will attack the killer bunnies instead of the players?

**Comment by molor** [comment]
@garbagemule, yes, that's right.

**Comment by garbagemule** [comment]
And you don't have `monster-infight: true` in your config-file, right?

**Comment by molor** [comment]
In my case, `monster-infight: false`

**Comment by garbagemule** [comment]
Alright, thanks, I'll give it a look soon. Thanks for the report :)

**Comment by garbagemule** [comment]
Fixed in next release. If you can't wait till then, here's a build with it: https://dl.dropboxusercontent.com/u/11723967/ma/MobArena.jar
