### ISSUE TITLE
Doesnt restore main scoreboard when leave arena

### ISSUE THREAD

**Issue by SaitDev** [garbagemule/MobArena#366]
When player leave or be forced leave the arena which enable `use-scoreboards` the main scoreboard wont restore

- MobArena: latest version 0.98
- Scoreboard plugin: QuickBoard
https://www.spigotmc.org/resources/quickboard-free-scoreboard-plugin-scroller-changeable-text-placeholderapi-anti-flicker.15057/

**Comment by garbagemule** [comment]
Actually, MobArena _does_ restore the main scoreboard when a player leaves. Specifically, the main scoreboard as provided by the Bukkit API is set as the player's scoreboard, so it doesn't get more "main" than that:

https://github.com/garbagemule/MobArena/blob/da094e0f5765677fbf4c5afa9f088cfe7155bf90/src/main/java/com/garbagemule/MobArena/ScoreboardManager.java#L47

Perhaps QuickBoard isn't manipulating the main scoreboard, but rather using its own?

**Comment by SaitDev** [comment]
I'm not sure since QuickBoard isnt open source, I'll try report this to quickboard's auther too.
Thanks for quick reply

**Comment by slipcor** [comment]
@garbagemule the player can have a scoreboard that is separate from the main scoreboard -> player.getScoreBoard() can be basically anything :)

**Comment by SaitDev** [comment]
QuickBoard 's scoreboard isn't manipulating the main scoreboard, they use getNewScoreboard() . In this case, can we restone the main scoreboard handle by other plugin?

**Comment by garbagemule** [comment]
To solve this issue, we need to store whatever scoreboard the player currently has, and restore it when the player leaves. I think this is very doable with the refactoring of the join/leave process in v0.100.

Maybe the solution is to simply add a ClearScoreboard/SetScoreboard step or something like that. However, #375 and #455 are related to scoreboards and worth taking into account.

**Comment by garbagemule** [comment]
@SaitDev I realize this issue is ancient, but do you still have a server running MobArena and QuickBoard? Would you be up for testing a potential fix to this issue?

**Comment by SaitDev** [comment]
@garbagemule sure i'll try a test build if u find out any solution for this

**Comment by garbagemule** [comment]
Awesome @SaitDev! Can you join the MobArena Discord server? I'll upload a release candidate build in there today. Makes it a bit easier to gather all the feedback from testers :)
