### ISSUE TITLE
Mobs aren't going towards me (big map)

### ISSUE THREAD

**Issue by Axlnh** [garbagemule/MobArena#368]
Hello,
So I'm configuring MobArena and everything is working fine with this good plugin but the only thing is that  I made waves of zombies in a flat arena. I'm making them spawn in the right top corner and I'm spawning in the left bottom corner. I can clearly see them with a 8 draw distance.
But when they spawn they just move a bit and just pack up and bug :/

Here's my wave config if needed : 

waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          wave: 1
          growth: fast
          fixed: true
          monsters:
            zombies: 10

Thanks in advance to anyone who will try to help :)

**Comment by garbagemule** [comment]
Check your server log - my guess is that MobArena has printed a warning claiming that the spawnpoints are too far apart.

Unfortunately, Minecraft's target system does not work well when the target (e.g. a player) is further than 16 blocks away. For example, if you have a skeleton 100 blocks away that you force to target you, it will freeze in place and not move until another player attacks it (takes aggro) or you enter the 16-block radius. As a result, MobArena does not attempt to set targets for mobs that are "too far away", and instead prints the warning you'll see in your log.

The workaround is to create more spawnpoints, and make sure each coordinate in your arena is within 16 blocks of at least one spawnpoint. Don't create too many (one per block is a bad idea), as too many spawnpoints can result in lag.

**Comment by Axlnh** [comment]
Thanks for your detailled answer.
My last question is : 
If I set a spawnpoint behind a wall with a whole, for example, will the zombies attack me (In a 16 block radius) ? Like, you got a 20 block wall and the spawnpoint is at the left corner and the whole is at the right corner (20 blocks) if you go close to the wall (zombies are behind the wall) will they understand that they have to go to the wall or will they stop walking at a 16 blocks radius?

Thanks in advance

**Comment by garbagemule** [comment]
All that matters for the actual targeting is the radius - it doesn't matter if the zombie has line of sight or not.

How the zombie *behaves* is completely out of MobArena's control. MobArena just spawns a zombie and sets its target to a player. Everything else is vanilla behavior :)

Closing this as a non-issue.
