### ISSUE TITLE
Major Inventory Issue

### ISSUE THREAD

**Issue by Zoneman1972** [garbagemule/MobArena#369]
Hi there. Firstly may I say I absolutely love this plugin. It is adding so much extra entertainment to my server. 

Unfortunately though, I have found a rather annoying bug which is crippling my server economy drastically. 

When a player types /Ma spec to watch over an arena match and then types /Ma leave to finish, their whole survival inventory is wiped clean and replaced with their creative inventory. 

As you can imagine this is allowing players to bring in masses of high value items (diamond blocks, enchanted books, etc) which they can then sell/use to boost their play abilities.

I would be extremely grateful if you could take a look at this issue as I have had to disable mobarena until this can be fixed. 

Thanks for your time. 

Is this plugin even being monitored and repaired???
14 days since this post went up and not 1 single response?!?!?

**Comment by jflory7** [comment]
@Zoneman1972 Are you using another plugin to handle multiple inventories? MobArena might not play nicely with other plugins that manage inventory.

**Comment by ct-martin** [comment]
@Zoneman1972 Hello, it's been a while since this issue was commented on, so if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
