### ISSUE TITLE
Conflict with GriefPreventionFlags flag

### ISSUE THREAD

**Issue by Timkat1994** [garbagemule/MobArena#373]
There is a conflict between MobArena and the _NoMonsterSpawns_ flag of  [GriefPreventionFlags](https://www.spigotmc.org/resources/griefprevention-flags-from-the-creator-of-griefprevention.10280/). When you enter an arena inside a claim using this flag, spawning is normal within the arena, but **mobs vanish when struck** and do not count towards the kill count.

The solution might seems simple-- just don't use the _NoMonsterSpawns_ flag-- but this flag only disables natural hostile mob spawning (zombie, skeleton, etc.) and still allows the player to spawn hostile mobs via the /summon command, through eggs, and mob spawners. This makes it extremely useful for creating areas where players can still access passive mobs (sheep, cow, etc.) and the server owner can have the freedom to decide where they want hostile mobs to spawn. For example, on my server, I've been able to create monster-filled dungeons and traps within the spawn area and not have hostile mobs running amok.

I could also place the arena outside the claim and ignore the conflict, but my issue here is that I _want_ the arena to be located within the spawn town. I cannot have both the _NoMonsterSpawns_ flag of GriefPreventionFlags and MobArena work in the same space currently.

I have not noticed any console errors.

**Comment by garbagemule** [comment]
MobArena actually sets the spawn flags in the world when the arena starts, meaning it's done everything it possibly can to enable monster spawning, so my guess is that the compatibility issue lies on the GriefPreventionFlags-side of things. The plugin is closed source (*sigh*), so I can't look into potential issues of its inner workings. Afraid I can't do anything about this, friendo, sorry.

**Comment by Timkat1994** [comment]
Aw, well, thank you anyways! I'll see about messaging the GP Dev about this.

P.S. I've used MobArena for over 6 years now and just wanted to say I've really enjoyed the plugin and I appreciate what you do!
