### ISSUE TITLE
upcoming 1.12 release breaks Mob Arena

### ISSUE THREAD

**Issue by frizzbee30** [garbagemule/MobArena#374]
h, you may already be aware, but if not the upcoming 1.12 version release creates an issue with the plugin.

Thanks

https://pastebin.com/CxBvaRLf

**Comment by garbagemule** [comment]
Thanks for reporting. Hook me up with a build or a guide to getting 1.12 going and I'll get fixin'.

**Comment by PugaBear** [comment]
[Here's an example from Gamealition/GPrism](https://github.com/Gamealition/GPrism/commit/c2210e613a46fa39a7ebaf25d21623ed1d626206#diff-046cc6b0b7668d5e5da31b52241bcea5R41)

[Here's an official, messy tutorial](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

Hope that helps

**Comment by garbagemule** [comment]
Right there on the front page. Need new glasses...

**Comment by garbagemule** [comment]
Here's a build with the fix if you want to try it out: https://www.dropbox.com/s/1c5lljfq6pryf8n/MobArena.jar?dl=0

**Comment by frizzbee30** [comment]
Thanks, that's great  :)
