### ISSUE TITLE
Spawning Wolves

### ISSUE THREAD

**Issue by dadee971** [garbagemule/MobArena#378]
Hi,
I'm on Spigot: CraftBukkit version git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT), and i'm using version 0.98 MobArena.

Each time a game is started many wolves are spawning with players.
May be the dogs they owned i don't really know.
How to prevent tamed wolves/wild wolves to teleport in arena?

Bests regards.

Edit:
I have kill all tamed on the server, and those wolves are still spawning at the game start.
My config: https://pastebin.com/XYPZfPRL

**Comment by garbagemule** [comment]
Are you using the My Items class?

**Comment by dadee971** [comment]
Yes i améliorer.

**Comment by dadee971** [comment]
Yes i am

**Comment by ct-martin** [comment]
@dadee971 Hello, it's been a while since this issue was commented on, so if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
