### ISSUE TITLE
Add support for named potion types

### ISSUE THREAD

**Issue by SXRWahrheit** [garbagemule/MobArena#382]
_Edited by garbagemule: This turns out to be a limitation in the way that the item parser currently handles data values. Only numbers are supported, so `INSTANT_DAMAGE` and the other names simply won't result in valid items._

Just gives water bottles. I use class chests for woodland, but water bottles are given on initial class spawn in underdome as well.

https://hastebin.com/iwacuheteb.scala

**Comment by SXRWahrheit** [comment]
From the log:

[16:44:43] [Server thread/WARN]: [MobArena] Failed to parse item: splash_potion:INSTANT_DAMAGE:30
[16:44:43] [Server thread/WARN]: [MobArena] Failed to parse item: splash_potion:POISON:8
[16:44:43] [Server thread/WARN]: [MobArena] Failed to parse item: splash_potion:INSTANT_HEAL:20

**Comment by garbagemule** [comment]
Holy poop nuggets. I finally figured out what was wrong here.

You are most likely running a Minecraft version prior to 1.9. Back then, there was no Material enum value called `SPLASH_POTION`, it was just `POTION` with higher data values. I've updated the Item Syntax page to reflect this.

**Comment by SXRWahrheit** [comment]
I'm running 1.12.2 tho

**Comment by garbagemule** [comment]
Ah, in that case it's a matter of the data values being off. It looks like MobArena doesn't support named data values. It uses this map that slip implemented for the odd transition phase between... 1.9 and 1.10 I believe?

https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/util/ItemParser.java#L28-L40

**Comment by SXRWahrheit** [comment]
Word, I'll try that. Named potion types is probably preferable given that future updates will break/change data values :)

**Comment by garbagemule** [comment]
Yep, I've added a little note to your opening post and reopened the issue so we can keep track of this. The item parser itself is due for a proper rewrite, but I think it will be in a slightly bigger sweep that also allows for splitting the config-file a bit.

**Comment by SXRWahrheit** [comment]
Cool. Having separate configs for each arena would be useful so I can manage them more easily :)

**Comment by SXRWahrheit** [comment]
ily @garbagemule
