### ISSUE TITLE
Allow for grouping rewards in addition to randomized rewards

### ISSUE THREAD

**Issue by garbagemule** [garbagemule/MobArena#386]
The current functionality of randomized rewards often forces people to stick with just one reward for each wave when they want full control and predictability in the rewards. This also means that rewards must be granted in a staggered way if one wants to reward a "set" of items (e.g. waves 5, 6, 7, and 8 each give a piece of diamond armor instead of wave 8 giving the entire set).

A backwards compatible way to improve this functionality would be to introduce higher-level specification constructs, `all` and `random`. They could work like this:

    '5': all(dirt, gravel, stone)
    '7': random(iron_ingot, gold_ingot)

With this, wave 5 would result in a reward set of dirt, gravel and stone, and wave 7 would result in a randomized reward of either and iron or a gold ingot. The default behavior would be `random` for backwards compatibility.

If we also allow for *nesting* of these constructs, we would have four combinations (random item, all items, random set, set of random items):

    '1': random(dirt, stone)
    '2': all(dirt, stone)
    '3': random(all(dirt, stone), all(diamond, emerald))
    '4': all(random(dirt, stone), random(diamond, emerald))

Waves 1 and 2 are trivial. Wave 3 results in a random set of two items, either dirt + stone or diamond + emerald. Wave 4 results in a set of two items, where each item is randomly picked from a set of two, resulting in four possible combinations (dirt + diamond, dirt + emerald, stone + diamond, stone + emerald).

Edit: Changed from `one` to `random` for clarity.

**Comment by mibby** [comment]
Has there been any progress towards this proposed rewarding change? I'm all for it as it would allow rewarding between a random selection of items, as well as always provide a set defined reward on completion of a round. For example, if a player beats wave 100 of MobArena, you could always provide them with $500 and a random reward between 122, 443, & 397:5:1.

I also noticed that the ```        after:``` rewarding provides people the reward when they get to the round number, not necessarily on completion of it.

**Comment by mibby** [comment]
@garbagemule Bump. ^^

**Comment by garbagemule** [comment]
Ah sorry. No progress yet. I'm a bit swamped until mid-November, but I plan on going ham on the rewards stuff (this one and command rewards) then.

As for one-offs, that is unlikely as it requires a persistence layer that MobArena does not have (yet). It's the same limitation holding back global leaderboards/stats. I'll get around to that eventually. In the meantime, I'd like to hear how other plugins handle this sort of thing; yaml files, databases (which ones?), in-game things?

**Comment by mibby** [comment]
I'll look around to see what I can find but the only type of one-off reward system that I can recall is CrateReloaded supporting permission lookup. So you could reward someone an item and a permission node, then next time it tries to reward players with an item, it checks if they have that permission already. Only problem with that is cluttering the permissions file and perm look-up deadlocking for groups that have wildcards inheritance (admin) or deadlock when there is no fallback reward if they have permission for everything.

**Comment by Nesseley** [comment]
Would be nice to have the chance of getting a reward or nothing as well.
`random(dirt,  nothing)`
You either get a dirt or you get nothing.
