### ISSUE TITLE
Class Signs dont work

### ISSUE THREAD

**Issue by Kryzomine** [garbagemule/MobArena#388]
When I join a MobArena , I cant choose a class from the Class signs and btw the Iron block isnt working too ... i Think im too stupid for that to setup . Maybe someone can help me ? I read somewhere that MobArena isnt compatible with Bukkit , I have bukkit and everything is working fine but the class signs and the iron block

**Comment by ct-martin** [comment]
@Kryzomine The [documentation](https://mobarena.readthedocs.io/) has been recently made much easier to read, could you please try following the new(er) version and see if it works for you? If you're still having this issue, [you can find us in a couple places](https://github.com/garbagemule/MobArena#getting-help) (if we're available), but if that doesn't work could you please resubmit this with the new issue template? Thank you.
