### ISSUE TITLE
BlockState change upstream in spigot may break container updating in arenas.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#394]
@garbagemule Heads up. While I have not personally confirmed whether this breaks in MA yet, I have confirmed that this does break chest updating in PVPArena and LogBlock chest rollback for me. Figured I'd let you know just in case the API wasn't being used correctly according to spigot, as I recall MobArena has a feature to allow for chests to receive fill items in waves.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e#src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java

RE: https://github.com/slipcor/pvparena/issues/321

**Comment by garbagemule** [comment]
Thanks mibbles. I'll look into it.

**Comment by mibby** [comment]
@garbagemule For reference https://github.com/slipcor/pvparena_modules/commit/febd72611930e712eaad5cc28c42fd6c956ce91b

**Comment by garbagemule** [comment]
Seems like MobArena won't be affected by this, since it never calls the `update()` method.

Reopen if it actually turns out to be an issue :)
