### ISSUE TITLE
Where is the command /ma ready ?

### ISSUE THREAD

**Issue by Oruss7** [garbagemule/MobArena#396]
I see a **/ma notready** command. But where is the ready ? ^^

Thanks

**Comment by ct-martin** [comment]
`/ma ready` makes more sense for marking a player as ready (same effect as iron block, request for this in #407 ). I propose `/ma isready` for this should it be added.

**Comment by jflory7** [comment]
Since @ct-martin filed a detailed version of this issue and also hopes to work on this feature, I'll close this ticket as a duplicate, and we can track progress in #407.

@Oruss7 Thank you for your time filing this ticket!

**Comment by ct-martin** [comment]
@jflory as I tried highlight in my comment this issue is a request for a
feature to see who has a ready status for the arena, not a  replacement for
the iron block is. I would request reopening of the issue.

**Comment by jflory7** [comment]
@ct-martin Oh, I see. It's unclear to me what @Oruss7 is asking for, though. I'd prefer to see this filed as a new issue using the template. That will make it easier for us to understand and think through.

**Comment by Oruss7** [comment]
I was asking for `/ma ready` command. But anyway, i track #407  now. 

Thanks.
