### ISSUE TITLE
/ma ready as alternative to iron block

### ISSUE THREAD

**Issue by ct-martin** [garbagemule/MobArena#407]
# Summary

* This issue is a…
    * [ ] Bug report
    * [x] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
Ability to use `/ma ready` as an alternative to an iron block

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [x] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**:
Same effect as hitting an iron block
**Does it need new or changed commands? What are they?**:
Yes, addition of `/ma ready`
**Does this feature affect other parts of MobArena?**:
Same as iron block join

**Comment by garbagemule** [comment]
I'm not entirely sure why I never implemented this. It's a good idea, and it's quite simple. Good first issue :)

**Comment by jflory7** [comment]
@ct-martin Earlier, I remember saying you were interested in working on some issues. Do you want to be assigned this ticket?

**Comment by ct-martin** [comment]
I can do this, it *should* (I say now) be quick to do.

**Comment by garbagemule** [comment]
Be aware that there's a chance you'll "need to" copy/paste some class chest logic. I don't recall if I ever refactored that part out into a utility function or not. It's ugly. Here be dragons.

**Comment by Haileykins** [comment]
I would be able to get this worked on. I can start now!

**Comment by Haileykins** [comment]
I didn't read well. Looks like CT-Martin got this one

**Comment by garbagemule** [comment]
@Haileykins I've added the issue to the April Sweep, so it's up for grabs if you'd like to take a stab at it. Feel free to have a look at the other good first issues as well.

**Comment by Haileykins** [comment]
I'll look into it when/if I have time. I also have other things to work on and life is a pain in the ass if you believe it lol! Happy to poke around the code

**Comment by garbagemule** [comment]
Added in 977df0b9f47a41ae304b58d5e51a61f5cdd98244 and included in the next release.

Thanks @SaitDev!
