### ISSUE TITLE
Create documentation for MobArena modes

### ISSUE THREAD

**Issue by jwflory** [garbagemule/MobArena#408]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [X] Other issue
    * [X] Question 
* **Describe the issue / feature in 1-2 sentences**: There are multiple modes in MobArena, like Setup and Edit mode; would a dedicated page / including an explanation on another page be helpful?

# Background

**What does it do?**: Explains different MobArena modes side-by-side, to help users and developers

**Does it need new or changed commands? What are they?**: No

**Does this feature affect other parts of MobArena?**: No

# Details

I mostly want to have a conversation about it first, before jumping in and writing something. Where can I learn more about the different modes? Does it make sense to have a new page or include it on an existing one? Or should we not do anything, if the modes are explained well in the pages that are relevant for them?

**Comment by garbagemule** [comment]
I tried looking through the wiki, and edit mode is actually not documented anywhere. I think it used to be explained either in the tutorial video or somewhere else, but it's completely gone now it seems.

I'm not sure there is a specific need to compare them, but there's massive room for improvement in usability. Edit mode is somewhat pervasive in the arena listeners in the code base, but essentially all it does is disable an arena and its protection, allowing for modifications to the "physical" arena structure. "Build mode" is probably a much better name for it.

I guess the TL;DR of the two modes is that setup mode is for "registering" stuff in MobArena, whereas edit mode is for changing the Minecraft world inside of a protected arena region.

**Comment by garbagemule** [comment]
#402
