### ISSUE TITLE
Modernize all existing documentation

### ISSUE THREAD

**Issue by jwflory** [garbagemule/MobArena#414]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [X] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: Update all documentation for the new [ReadTheDocs site](https://mobarena.readthedocs.io/en/latest/), modernize documentation for current codebase where needed

# Background

**What does it do?**: Improves usability of plugin and makes it more user-friendly

This ticket is more of a tracking ticket for the existing effort of modernizing documentation. I'll try to update this ticket as I progress through the documentation. Modernized documentation is the first critical part of my [community revitalization proposal](https://docs.google.com/document/d/1kEhNl9XedF8fIIpDzCG7816VLrPFTi0tYAZjq78Mens/edit?usp=sharing).

# Details

* [X] Announcements (#400)
* [X] Arena setup (#401)
* [ ] Class chests (#402)
* [ ] Commands (#413)
* [ ] Getting started
* [x] Item and reward syntax (#416)
* [ ] Leaderboards
* [ ] Monster types
* [ ] Permissions
* [ ] Setting up config file
* [ ] Setting up waves
* [ ] Using MobArena
* [ ] Wave formulas

**Comment by garbagemule** [comment]
#402
