### ISSUE TITLE
Update links to new docs

### ISSUE THREAD

**Issue by ct-martin** [garbagemule/MobArena#418]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [x] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 

Links on GitHub, DBO, & SpigotMC all point to the GH wiki, they should point to the new ReadTheDocs URL instead.

# Background

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [x] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Updates the documentation so that people can find the new, correct docs
**Does it need new or changed commands? What are they?**: 
Not unless you can use `/ma docs` or `/help mobarena docs` and get a link to the wiki or something like that
**Does this feature affect other parts of MobArena?**: 
No

**Comment by jflory7** [comment]
Nice catch. I think once all of our docs are updated, we can move forward with this. I'm assigning it to me for now. Once #414 is closed, this one can be unblocked.

**Comment by garbagemule** [comment]
See #402
