### ISSUE TITLE
Player dies by explosion but isn't removed from arena

### ISSUE THREAD

**Issue by RainOfPain125** [garbagemule/MobArena#419]
* MobArena version: Latest
* Server version: Latest version of Paper Spigot git-Paper-1286
* Plugins:
AutoSave, BlowableObsidians, BookUtils, CFD, Citizens, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, Essentials, EssentialsChat, FactionChat, Factions, HolographicDisplays, LuckPerms, MassiveCore, mcMMO, MessageAnnouncer, MobArena, Multiverse-Core, NoCheatPlus, OldCombatMechanics, Orebfuscator4, PaidRanks, PlayerHeads, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SuperTrails, Vault, WarningCategories, Wild, WorldEdit

# Summary

* This issue is a…
    * [X] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question

* **Describe the issue / feature in 1-2 sentences**: 
Being damaged by an explosion (creeper, tnt) (seemingly nomatter how far I am) kills me, and the arena still thinks im alive, yet it says [MobArena] RainOfPain125 blew up! and [MobArena] Enjoy the rest of the show! We have to /ma leave in order to get the arena session to end.

Also, splash healing potions don't seem to be working

# Background

* **Stacktrace** (if applicable):

**Comment by ct-martin** [comment]
@RainOfPain125 do you have any plugins/configs that might be changing the
creeper blast size or creeper damage? The messages from MobArena are likely
just the normal messages from when a player dies (they might just be an
effect rather than the cause).

**Comment by RainOfPain125** [comment]
None of the plugins would do such a thing that I know of

**Comment by garbagemule** [comment]
You'd be surprised at the kind of naughty stuff any given plugin will do to a poor, innocent explosion event. In a case like this, the most important troubleshooting step is to attempt to reproduce on an environment free of potential conflicts, i.e. with MobArena as the only installed plugin. If you can't reproduce it in a clean environment, it is a plugin conflict. If you can, it's a MobArena bug.

@RainOfPain125 You are in a unique position to test this as you are the one experiencing this issue. Please test in a clean environment and report back with your findings. Also, you left out a crucial part of the template. Please edit your first post to include the following:

>### Bug report
>* **MobArena version**: 
>* **Server version**: 
>* **Plugins**:

**Comment by jflory7** [comment]
@RainOfPain125 Were you able to re-test this in a clean server with no other plugins?

**Comment by garbagemule** [comment]
@RainOfPain125 "Latest" is not very helpful. If you provide a version number, you literally remove all doubt. By saying "latest", you assume that you are on the most recent build of something, and you have no idea if that's true. I've had people tell me they were on the "latest" version of MobArena when in fact they were three versions and almost half a year of updates behind, and the issues they were having had already been solved.

**Comment by garbagemule** [comment]
Please re-open if this is still an issue.
