### ISSUE TITLE
/ma leave not working

### ISSUE THREAD

**Issue by upsidedownapple** [garbagemule/MobArena#420]
# Summary

* This issue is a…
    * [X] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
when i join a arena and try to type /ma leave i get this error msg An internal error occured while attempting to peform this command 

# Background

### Bug report

* **MobArena version**: 0.99
* **Server version**: 1.12
* **Plugins**:  Coreprotect clearlagg RelaAutoBrodcast Oregenerator protocolLib Libsdisguises NocheatPlus FAWE HubThat Maxbans MobCoins Pex Vault protocolsupport Citizens MobStacker ASkyBlock ColoredTags CrazyAuctions EssentialsChat CommandNpc SuperVanish WorldGuard ChestShop SilkSpawners Multiverse-Core CitizensCMD discordSRV Mobarena Holographic displays CratesPlus

# Details

https://hastebin.com/oqayuforep.md on line 188 it starts

* **Stacktrace** (if applicable):

**Comment by ct-martin** [comment]
@garbagemule line 817, NPO in PlayerTeleportEvent. Line 954 another plugin gives a debug of "world must not be null"
Also, @jflory7, I think this was the same issue you were having that you haven't written a bug report for yet, could you verify?

**Comment by upsidedownapple** [comment]
Thx fixed it

**Comment by ct-martin** [comment]
@upsidedownapple could you tell us what fixed it for you? Thank you

**Comment by upsidedownapple** [comment]
i did /ma setup and changed the exit world thats wht fixed it for me it was because i downloaded a custom config with a world its exit world was set to something different

**Comment by ct-martin** [comment]
@upsidedownapple Thank you!
@garbagemule I'm going to file another issue for better handling of this error
