### ISSUE TITLE
Cant place armor stands in arena

### ISSUE THREAD

**Issue by JDittmerCOM** [garbagemule/MobArena#422]
When i'm in my mobarena (edit mode), can i not place armor stands in the mob arena .. outside of the arena can i place armor stands.
Is it a bug or is it blocked in the plugin?

**Comment by ct-martin** [comment]
@JDittmerCOM Thanks for filing a new issue, but it helps the developer team if you use the template. Could you please use the template and file a new feature request? Thanks!
