### ISSUE TITLE
Reward for boss missing transelate.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#427]
* This issue is a…
    * [X] Bug report
    * [X] Feature request

The sentence: [MobArena] Player killed the boss and won: X $ is missing from the announcements.yml
Would be nice to be able to transelate this as well! :)

MobArena version 0.99

**Comment by ct-martin** [comment]
@Nesseley I'm confused as to what you're looking for. Could you please rephrase your request in a more verbose fashion? Also, you didn't follow the entire template, so I'm going to close this issue. Please make a new issue with the "Feature request" section included.
