### ISSUE TITLE
Missing option to transelate a message.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#428]
* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question

* **Describe the issue / feature in 1-2 sentences**: 
Missing transelate option for "Player killed the boss and won:" in announcements.yml
I want to transelate this message to Norwegian, but I can't as there is no option to change the message.

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [X] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: Add a transelate for reward on killing the boss in the announcements.yml-file.

**Does it need new or changed commands? What are they?**: No

**Does this feature affect other parts of MobArena?**: No

# Details
Picture of the line I want to be able to change:
![image](https://user-images.githubusercontent.com/11998470/35213514-31e9d46e-ff5e-11e7-9b44-025020bef28f.png)

This line comes up when using the reward: $100 on boss-waves in config.yml

**Comment by garbagemule** [comment]
Right you are, this isn't translated at all: https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L607

Good first issue. Welcome to the April sweep.

**Comment by Haileykins** [comment]
I'll take the assignment on this one
