### ISSUE TITLE
Redstone doesn't work in lobby

### ISSUE THREAD

**Issue by hades200082** [garbagemule/MobArena#431]
# Summary

* This issue is a…
    * [X] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 

I cannot use command blocks with /sudo in the lobby because when a player is in the arena lobby they cannot activate redstone.

If I go to the lobby myself, I can activate the redstone and command block just fine.

# Background

### Bug report

* **MobArena version**: 0.99
* **Server version**: 1.12.2
* **Plugins**: 

- MobArena
- WorldEdit
- WorldGuard
- Sudo
- vault
- CraftConomy
- Coins
- Multiverse-Core 2
- Multiverse-Portals 2
- PermissionsEx

Note - I've tested this on a clean server with only MobArena installed and get the same result.

**What does it do?**: 

Inside a lobby create a trail of redstone and place a lever next to it.

While not in the arena, throw the lever - note that the redstone lights up.  Throw the lever back to turn it off.

Now join your arena so it puts you in the lobby.  Throw the lever again.  note that the redstone does not light up.

This issue prevents using sudo + command blocks to add "leave" buttons inside the lobby.

I also noted that the same sudo+command block method DOES work in the spectator area.

**Does it need new or changed commands? What are they?**: 

No?

**Does this feature affect other parts of MobArena?**: 

No

**Comment by garbagemule** [comment]
Thanks for the bug report :)

This is likely a result of MobArena being overly strict. It's pretty strict about a lot of stuff. When unorthodox setups like this actually work, it's usually the result of an oversight or a deliberate exception to the strict rules.

IIRC, redstone actually counts as physics events, so maybe MobArena is cancelling such events in the lobby by default.

**Comment by garbagemule** [comment]
Into the April sweep we go!

**Comment by Nesseley** [comment]
Confirming that this still is a bug.
Lever, buttons etc does not activate redstone in the lobby. (I can't pull the lever or push buttons at all)

**Comment by garbagemule** [comment]
So it turns out that MobArena just cancels any "right-clicky behavior" in the lobby.

IIRC this was a way to prevent players from accidentally killing each other and blowing stuff up in the lobby with magic spells and TNT and what have you. I think it's overzealous to just cancel all right clicks, and I also just managed to blow up my own lobby with a magic grenade by left-clicking. I'm gonna remove this check and see how things work out.
