### ISSUE TITLE
New boss ability modifier: "all" 

### ISSUE THREAD

**Issue by GriffinCodes** [garbagemule/MobArena#434]
# Summary

* This issue is a…
    * [ ] Bug report
    * [x] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: Currently, the boss abilities like pull, throw, and disorient have three types: `nearby`, `distant` and `target`. I would like a fourth: `all`

# Background

### Feature request 

* **Feature type**:
    * [x] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: Boss ability similar to some existing ones that effects all players in the arena, instead of just the nearby/distant ones, or the one it is targeting.

**Does it need new or changed commands? What are they?**: No

**Does this feature affect other parts of MobArena?**: No

**Comment by garbagemule** [comment]
Not a bad idea at all. Should be fairly easy to implement with the current setup, just a copy/paste and distance check removal for all applicable abilities.

I'll try to get this implemented by the end of April.

This is perhaps not a bad time to also dig through the boss "module" and gather some information about how it's used throughout the plugin to make way for a rework.
