### ISSUE TITLE
Iron Golems can't be damaged in MA

### ISSUE THREAD

**Issue by Pugabyte** [garbagemule/MobArena#436]
# Summary

* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: We tried putting an iron golem as a boss, and no one could damage it. Tried also making it a non-boss, just part of the waves, still couldn't damage it.

# Background

### Bug report

* **MobArena version**: 0.99.1-SNAPSHOT
* **Server version**: 1.12.2
* **Plugins**: `PlugMan, AutomaticInventory, Murder, SimpleAPI, SidewaysLogFix, wget, AutoMessage, MinigameHandler, Chairs, ProtocolLib, CustomParticleEffects, bnCore, MVdWPlaceholderAPI, FastAsyncWorldEdit, PermissionsEx, FeatherBoard, WhatIs, Tab, ServerListPlus, PlaceholderAPI, OneWayBlocks, InventoryChess, ActionBar, VoxelSniper, EditableSign, Alerts, TimeLock, StopPushing, dynmap, WorldEdit, OpenInv, WorldBorder, BuycraftX, Votifier, LibsDisguises, eZProtector, Super_Elytra, SQLibrary, DotCommand, Vault, TitleAdvanced, LWC, Quake, PlayerPoints, ChestCommands, PlayerVaults, MyCommand, GAListener, Herochat, Trading, PlotSquared, WorldGuard, ASkyBlock, Prism, Essentials, HeadDatabase, LiteBans, Dynmap-ASkyBlock, VanishNoPacket, Plot2Dynmap, CustomEnchantments, ConditionalPerms, SimplePets, Multiverse-Core, Citizens, mcMMO, MiniaturePets, MobArena, EssentialsProtect, Multiverse-Inventories, EssentialsAntiBuild, ParticleHats, EssentialsSpawn, WorldGuardExtraFlags, Denizen, PurpleIRC, PreciousStones, HeavySpleef, EnjinMinecraftPlugin, PermHelper, KillerMoney, HolographicDisplays, Depenizen, VoxelSniperRegions, Multiverse-NetherPortals, MultiWorldMoney, Minigames, Minigames-Regions`

**Comment by garbagemule** [comment]
That's a lot of plugins. Could I ask you to please confirm that this is a problem in vanilla MobArena as well?

I'll dig into this at the end of April.

**Comment by WakkaFlocka239** [comment]
It appears to have been WorldGuard blocking the damage of Iron Golems. Setting the region to Passthough allow seems to have fixed the problem.
