### ISSUE TITLE
No damage.

### ISSUE THREAD

**Issue by TheIntelloBox** [garbagemule/MobArena#444]
Hey,

https://hastebin.com/idicibezad.sql

On this map we don't take any damage. The mobs attack us but we don't lose hp. :D
Could you tell me what's the problem ? :D

Thanks ! :D

**Comment by Nesseley** [comment]
Maybe you have a worldguard region there aswell? 
You can check with standing in the arena and use /rg info

**Comment by garbagemule** [comment]
This is definitely a conflicting plugin. MobArena doesn't cancel damage to arena players - in fact, it "uncancels" damage to arena players, but the cancellation can still get overridden by another plugin.

Typically it's WorldGuard or if the arena is located in or close to the spawn area of the world.
