### ISSUE TITLE
Case sensitivity in commands

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#446]
* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
Players can't type commands in capslock in arena.
/MA L and /ma L does not work, while /ma l does.
Some younger players thinks that /ma 1 (one) is the command and if i type "Use /MA L" it doesnt work. I fixed this by adding it in as a extra command in the config, but it should work form the beginning.
Also /ma S /ma J does not work aswell

### Bug report

* **MobArena version**: MobArena v0.99
* **Server version**: 1.12.2
* **Plugins**: Not needed

**Comment by garbagemule** [comment]
Thanks for submitting this issue :)

So this isn't actually a bug. Case sensitivity in commands is not a deliberate choice, but it isn't stated anywhere that the commands can be used in a case insensitive way. It's more of an oversight or lack of consideration, really.

Renaming and recategorizing.

**Comment by garbagemule** [comment]
Fixed in the next release!
