### ISSUE TITLE
Delay between waves

### ISSUE THREAD

**Issue by PetrichorCraft** [garbagemule/MobArena#449]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
I'd like to have the ability to set a delay between waves, when all mobs must be killed before moving on. As it is, players take varying times to kill the mobs, so the current "wave-interval" doesn't allow a set amount of cooldown between waves.

# Background

### Feature request 

* **Feature type**:
    * [X] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
It allows you to set a wave-delay between when the last mob of a wave was killed, and when the next wave begins.
**Does it need new or changed commands? What are they?**: 
No new commands.
**Does this feature affect other parts of MobArena?**: 
This may affect the current wave-interval. I believe that it would replace it, as this could be used both when the mobs need to be killed first, and when they don't. The only thing is that wave-interval is total time, versus time after mob death.

# Details

* **Stacktrace** (if applicable): 

Thank you for taking a look at this, whether it is implemented or not. :)

**Comment by Haileykins** [comment]
This is something I personally have thought to need to be a feature. I do not know all to well how to use timers and delays in Spigot/Java, but it should be a simple (in English): If lastmob dead, start timer (x seconds) start new wave. I can look into this if I have the time.

Note to staff on project, do not assign this to me unless no one else is interested in looking at it as there's no guarantee I can get it done, but I will take a look today and see how the waver-interval works, and use that to base this idea

**Comment by garbagemule** [comment]
This requires changes throughout the waves system - config-file (and thus the parser), ArenaImpl, MASpawnThread, possibly all of the waves logic if there has to be any sort of additional configurability in it.

I'll say that before an arena session rework, the only possibility is a per-arena wave delay that is fixed and forced in between all waves. But we need to look into the different wave-specific settings and see how they impact this functionality.

Not a good first issue, and needs more investigation.

**Comment by garbagemule** [comment]
@PetrichorCraft I may have an implementation of this feature ready. Would you like to come on Discord so I can send you a build for testing? :)

**Comment by PetrichorCraft** [comment]
Everything appears to work. Thank you very much! ^.^
