### ISSUE TITLE
The ability to give regular mobs potion effects.

### ISSUE THREAD

**Issue by PrinceOfIonia** [garbagemule/MobArena#453]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
Simple as the title says! The boss has the (potions:) config option, so it shouldn't be too hard to port this over to regular mobs.

# Background

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [X] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Gives mobs the ability to have potion effects when they spawn, customizable in the waves part of the config.
**Does it need new or changed commands? What are they?**: 
No new commands would be required.
**Does this feature affect other parts of MobArena?**: 
It shouldn't, since this only adds to the customizable ability to the player.

# Details
This is pretty much all I want, but it doesn't work currently in the latest version, because I guess regular mobs aren't programmed to be able to take the (potions:) config option.

EXAMPLE ----> http://prntscr.com/jdb4a8

**Comment by PrinceOfIonia** [comment]
Yeah! See what I mean! Although, I think zombies only jump when they need to go up 1 block.

**Comment by garbagemule** [comment]
In the provided example, do all mobs in the wave get all the potions listed? How would we go about giving different mobs different potions?

**Comment by PrinceOfIonia** [comment]
Well, a good starting point would just make (potions:) work for mobs, and every mob spawned that wave will get the potion effect. Giving different mobs different effects in the same wave is a little tricky, prehaps maybe have the potions template work like this, (potions: [mobtype]:[effect]:[amplifier]:[duration]) but it's just a thought, for now I believe if you're going to implement this, just have (potions:) be able to work on mobs, and all mobs get the effect.
