### ISSUE TITLE
Upgrade waves being configurable by chests

### ISSUE THREAD

**Issue by Swatacular** [garbagemule/MobArena#456]
# Summary
* This issue is a…
    * [ ] Bug report
    * [x] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
Upgrade waves being configurable by chests

# Background

### Feature request 

* **Feature type**:
    * [x] Arena configuration
    * [x] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Using the class chest system that is already in place, it would be very nice and easy for people who do not have FTP access to the server to change the upgrade waves if we could do it from within the game.

while it may be alot of chests, it may help to be able to set the chests up whereever they are on the world (very large control room outside of the arena regions) 

or possibly have extra chests under the first class chest, and just select the next chest down for each upgrade wave that happens.

**Does it need new or changed commands? What are they?**: 
It may need commands that link the chest to a wave, class and arena.

**Does this feature affect other parts of MobArena?**: 
Yes, it will affect how mob arena decides to distribute upgrade waves.

**Comment by garbagemule** [comment]
There is a significant overlap between this and #457 

I feel that handling this specific case is opening a can of worms: What's next? Supply waves? Boss waves? There has to be a much more concrete, well-described example of how this could work, and why it makes sense to tackle upgrade waves specifically and not the other waves. This is way too vague.

**Comment by PeterMaffay89** [comment]
I vote for this feature.
By now, classes can be configured by using class-chests. But there is no similar way to upgrade those specific classes.

The setup could look similar to linked class chests:
`/ma classchest <class> <upgrade-wave-name>`

Example:
`/ma classchest Knight upgrade1`
config.yml:

config.yml:

    waves:
      single:
        upgrade1:
          type: upgrade
          [...]
          upgrades:
            Knight:
              classchest: [...]
