### ISSUE TITLE
Using commands in upgrade waves

### ISSUE THREAD

**Issue by Pendragon1111** [garbagemule/MobArena#468]
* This issue is a…
    * [x] Feature request
* **Describe the issue / feature in 1-2 sentences**: 
An option similar to the reward wave "command" feature, but for upgrade waves. Allows for running commands as an upgrade in a similar fashion.

### Feature request 

* **Feature type**:
    * [x] Arena configuration
    * [x] New config settings
    * [x] Rewards

**What does it do?**: It would allow more control over the things we're able to give players within the arena. Commands, for my part, would be used to give specific armor and weapon upgrades that can't be achieved otherwise, but I can also see heavy use for things like custom reward point systems, temporary potion buffs, permanent potion buffs, new spells, among other things.

In more specific terms, an upgrade wave could include a line like:
`'10': cmd($50):/points <player> add 50'`
Meaning, at wave 10, the player recieves 50 "points". In this example, points would be something specific to mobarena, spendable at.. for example, signs with commands and custom costs that take those points. It'd be a neat way to allow mobarena shops, which is just one possible use for this.

If you'd like any more examples, let me know below; but for now it's late, so I'll post this as is. Thank you for your consideration.

**Comment by garbagemule** [comment]
Great idea.

I think this requires a bit of a rework of the upgrade waves, but I don't think it's entirely too much work. The way the Things API currently works for class items should be enough for upgrade waves in the case of armor at least. Weapons are a bit different. Definitely requires a bit more investigation before we can get to an implementation plan.

**Comment by garbagemule** [comment]
@Pendragon1111 I might have a basic rework of the upgrade waves sorted out. Would you be able to come on Discord for testing?

**Comment by Pendragon1111** [comment]
Yes, but not until tomorrow; I'm about to drive to the beach for the day haha.

I'll join the ma discord tomorrow, or my tag is ArthurPendragon#0547
