### ISSUE TITLE
Boss monster can not be wither skeleton.

### ISSUE THREAD

**Issue by iceypotato** [garbagemule/MobArena#475]
# Bug report

**Short description**
When I set up a boss wave, and I set the monster to wither_skeleton in the config, there will be an error in the console that says: 
`[19:17:14 WARN]: [MobArena] Wave 'boss5' for arena 'big1' could not be parsed.`

**Reproduction steps**

Put this in the config file:
`        boss5:
          type: boss
          wave: 30
          monster: wither_skeleton
          health: 1250
          abilities: shuffle-positions, throw-nearby, obsidian-bomb`

**Details**

* **MobArena version**: 0.1.2
* **Server version**: Spigot for MC 1.8.8
* **Stacktrace** (if applicable): none

**Additional info**

I think it worked on older versions of MA.

Also I resubmitted this ticket.

**Comment by garbagemule** [comment]
Closing this as there's no reason for the old ticket to be closed.
