### ISSUE TITLE
1.13 compatibility.

### ISSUE THREAD

**Issue by TheIntelloBox** [garbagemule/MobArena#479]
Hello,

MobArena doesn't work in 1.13. Could you fix it ? :)

Thanks !

**Comment by PrinceOfIonia** [comment]
Hi, 1.13 was a pretty scary update for Spigot and most of the plugins, I heard garbagemule is already trying to solve most of the bugs in 1.13, he mentioned that most of the code has been switched up a little so it might take some time, but we'll see!

**Comment by jarlpenguin** [comment]
Does the compatibility layer refuse to work?

**Comment by garbagemule** [comment]
There are dev builds for 1.13 available for test on Discord.
