### ISSUE TITLE
Set time interval before next wave

### ISSUE THREAD

**Issue by Oruss7** [garbagemule/MobArena#481]
# Feature request

**Short description**
Please set time interval before next wave. 
I have `clear-wave-before-next: true` but when last mob is killed, next wave spawn immediatly and creeper for example blow up players... A interval time before last mob killed and next wave spawn will be appreciated.

**Implementation details**
Maybe add a new config (in second):
`clear-wave-time-before-next: 20`

**Additional info**
conf: https://pastebin.com/c5qzpjPq

Thanks you !

**Comment by garbagemule** [comment]
Duplicate of #449

**Comment by garbagemule** [comment]
@Oruss7 as mentioned on #449 I can give you a build with an implementation of this feature on Discord if you want :)

**Comment by Oruss7** [comment]
yes i want ! thanks @garbagemule and all team MobArena !
