### ISSUE TITLE
Can't give notch golden apples as rewards

### ISSUE THREAD

**Issue by Ferocimo** [garbagemule/MobArena#494]
Hello,

As said in the title, I didn't find any way to give Notch's golden apple as rewards (other than with a command reward, which would be a glitchy way of avoiding the issue). Tried putting : "golden_apple:1:5" to give 5 golden apples like I want to, which worked on prior versions of MobArena, but it no longer works.
Error "Failed to parse reward" now appears when reloading MobArena.

Thank you for looking into this.

**Details**
* **MobArena version**: 0.103
* **Server version**: git-Paper-1230, MC 1.12.2

**Comment by Ferocimo** [comment]
Okay, I will try downgrading to 0.102, I'll wait for the 0.103 to be more stable then. Thank you for your reply.

**Comment by garbagemule** [comment]
Thank you for your patience :)

**Comment by Ferocimo** [comment]
No worries. But actually the error is still happening on 0.102. What could I do ?

**Comment by garbagemule** [comment]
Let's track this on #489, since they are basically the same thing :)
