### ISSUE TITLE
Let pets teleport

### ISSUE THREAD

**Issue by sepulzera** [garbagemule/MobArena#497]
# Feature request

**Short description**

Classes may have pets like wolves. Pets are invincible and should be available for the class through the whole match. But when pets leave the arena (e. g. falling through a hole) they get removed (like any other entity).
On the other hand, pets can not teleport to the player if their distance increases too big, like they do in vanilla. But they should, in case they get stuck.

**Implementation details**

Pets should be able to teleport per default. It could be configurable via a per-arena setting to opt-out.
It should not be bound to the allow-teleporting variable. You may want to let your pets teleport but still not let players teleport.

**Additional info**

* This could also affect hostile mobs or animals inside of the arena, maybe via a separate setting. But it may require further conditions and therefore discussion. 
* It should never be permitted to leave the arena via teleporting. Only back or inside of the arena.

**Comment by garbagemule** [comment]
Sorry for the super late reply.

Currently _all_ entity teleport events are cancelled if the teleportation is from or to the arena region. I can see that it makes sense for pets to teleport back to their owners, and I think it is a pretty simple fix. Would you be interested in testing out a dev build if I whip something up? If so, please hop on the MobArena Discord server :)

As for allowing hostile mobs to teleport, I think it would make sense in a lot of cases, but some people have pretty large arena regions that cover more than just the arena floor for the sake of protection (e.g. spectator and lobby areas), and if the physical arena structure isn't a perfect box, there is a risk that for example an Enderman could teleport to a spot that can't be reached by players.
