### ISSUE TITLE
NullPointerException: null - Location.getBlock

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#501]
Paper dev 366 (Spigot 1.13.1)
MobArena 0.103.1-SNAPSHOT as of commit https://github.com/garbagemule/MobArena/commit/d9b9b2493cbe8eb7e4dafd66c35a954afa0df338

```
[06:07:19] [Server thread/WARN]: [MobArena] Task #196321 for MobArena v0.103.1-SNAPSHOT generated an exception
java.lang.NullPointerException: null
	at org.bukkit.Location.getBlock(Location.java:100) ~[patched_1.13.1.jar:git-Paper-366]
	at com.garbagemule.MobArena.util.ClassChests.assignClassFromStoredClassChest(ClassChests.java:29) ~[?:?]
	at com.garbagemule.MobArena.ArenaListener$1.run(ArenaListener.java:1150) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-366]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-366]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

This error spams when a player tried joining the MobArena in a 1.13.1 environment. I use class chest locations instead of config based inventories.

**Comment by garbagemule** [comment]
The world of the Location is null. Try resetting the class chest locations or double check the world name in the class chest location in the config-file. The only other thing I can think of is the world of the location not being loaded by the time MobArena parses it.

**Comment by mibby** [comment]
The location and world exists as configured from 1.12.2. It is located in a separate ```void``` world with the actual mobarena build. The chests exist and have all their correct item contents.

I can only assume perhaps something changed with 1.13 where MobArena is not able to load the chunk to get the data to parse. Or perhaps it is a compatibility issue with Paper (Spigot Optimized Fork)?

**Comment by SaitDev** [comment]
Can you try with async chunk loading turned off?
`settings.async-chunks.enable` false

**Comment by garbagemule** [comment]
Yeah it's probably a null world (Paper's Bukkit source is probably different from the Spigot one, because line 100 in the Bukkit source I have points to a line that can't throw an NPE). MobArena just blindly trusts that the world exists and is returned by Bukkit's getWorld(String) method. But if the world isn't loaded, chances are that the method returns null. MobArena can't look up chests in or teleport players to null worlds.

As for solving the problem, I'm not sure that it is MobArena's responsibility to ensure that worlds are loaded and "ready". But if a null world is returned anywhere, MobArena should probably throw an error instead of blindly trucking on.

Try moving the exit warp and a class chest up close to the arena structure if they aren't already, stand next to them, then reload MobArena and try again. That should constitute optimal world/chunk circumstances. If it still fails, please try on Spigot.

**Comment by mibby** [comment]
MobArena use to call the chest chunk location when it needed to load it in 1.12 and the world _does_ exist (is loaded). It teleports players to the same world the chests are located in, just the chests aren't near the arena. I'll try moving the area so it loads the chests in the same chunk the lounge is at, but it seems like a deeper issue if it use to work with 1.12.

As for the exit warp location, it should be using the player's initial join location. So if a player joins from ```world``` into ```void```, when they leave they should be brought back to their home. ```world``` should be a valid world that's loaded. Moving the exit location is not ideal and the only real workaround I could see is forcing people to spawn where chunks are always kept in memory.

@aikar Issue is with paper chunk changes?

**Comment by aikar** [comment]
no this has to deal with worlds not chunks. they are different.

**Comment by mibby** [comment]
The only other thing I can think of is it being an issue with Multiverse-Core. I've been using @Brokkonaut's updated fork here https://github.com/Brokkonaut/Multiverse-Core/tree/updated and just tried reverting the removal here https://github.com/Brokkonaut/Multiverse-Core/commit/46f973f95daabc02a0c286ab47f6f8b35ddcde92#diff-8aab397e345c135301820ecdc68306acL39. However, still no luck on my end. MobArena produces the errors despite the worlds existing.

**Comment by mibby** [comment]
I spent a while getting to the bottom of this issue. It seems to be an issue with the plugin PlotSquared. I'm not sure why it works with 1.12 and breaks with 1.13, but the issue does seem to stem from PlotSquared being installed. I'll forward the issue to the correct developers. :)
