### ISSUE TITLE
Inventory loss when dying while spectating.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#502]
MobArena compiled as of commit https://github.com/garbagemule/MobArena/commit/d9b9b2493cbe8eb7e4dafd66c35a954afa0df338
Paper dev 405 (Spigot 1.13.2)

Players in the spectate state - either by joining via ```/ma spectate``` or being brought to spectator when dying in an arena with the game still on-going - can take damage and die. Tested with taking fall damage, unsure if you can also starve. If you die in the spectator state, you lose your outside inventory. Shouldn't spectators be invulnerable similar to being invulnerable when in the lobby?

**Comment by garbagemule** [comment]
What state is the player in after respawning? Where do they respawn? Are they still "spectating" so MobArena wants them to /ma leave? Or do they get thrown out back to where they joined or the exit warp?

**Comment by mibby** [comment]
You get kicked out of the arena and brought to the exit location. Except your inventory is wiped. Typing ```/ma leave``` does not kick you out as you are no longer part of the arena.

**Comment by Nesseley** [comment]
For later: This is a issue when the spectator area is NOT a part of the arena area (/ma setup part). 
Players can starve, take dmg and pvp.

Easy fix for server-owners: Make the spectator area in the arena area (the golden axe in setup)

**Comment by garbagemule** [comment]
During today's MobArena jam we found a fix for this. @mibby if you'd like to test it out before I push and release it, that'd be awesome - I'll throw it up on Discord if you hop on :)
