### ISSUE TITLE
Leaderbaord only shows one player

### ISSUE THREAD

**Issue by Klawdek** [garbagemule/MobArena#506]
**Short description**

The leaderboards only display the last player to play instead of multiple players.  Only one line is listed and it gets replaced with the next one rather than a list being made.  That is player X plays and is listed on leader board.  Then player Y plays and instead of be listed on leader board along with player X it replaces player X.  

When I join the arena, X doesn't work.

**Reproduction steps**
Have one player play in the arena and then have a nother player play in the arena and look at the leader board.

**Details**

* **MobArena version**: 0.103
* **Server version**: not sure
* **Stacktrace** (if applicable): https://pastebin.com/gB5qbcnr

**Additional info**

**Comment by Nesseley** [comment]
Leaderboard is only displaying last session played of the arena. It's not tracking and saving any stats, only showing last game played. :)

But I don't know about the error. So someone else have to check on that.

**Comment by SaitDev** [comment]
The error link is fake. Please do not provide fake error if there is not any error messages on the log

**Comment by SaitDev** [comment]
Opps. That the default link from the template :D

**Comment by garbagemule** [comment]
Like Ness says, this is the intended behavior of the leaderboards. There is a suggestion for persistent stats in #162. If that issue isn't sufficient, please make a new feature request following the template.

**Comment by Klawdek** [comment]
I am sorry I had no idea what scoreboard vs leaderboard meant.  Perhaps it could be made more clear in the docs.  My players pointed this out to me as something "broken".  So it seems that players expect it to behave that way the first time they look at it and when it does not they think it is broken.

**Comment by garbagemule** [comment]
No worries. Lots of people want persistent stats for display on signs and server websites. We'll get around to it eventually...
