### ISSUE TITLE
Certain mobs de-target players and die if it is not night time.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#525]
Paper dev 585 (Spigot 1.13.2)
MobArena v0.103.2-SNAPSHOT (discord test build 02/16/19)

Would it be possible to modify the AI of MobArena mobs at all? Zombies die during the day and spiders become non-aggressive and start climbing walls / get out of reach of the player. The world's difficulty is ``NORMAL``.

I'm able to work around this issue slightly by setting the WorldGuard region with a flagged time-lock to night, but then the night continuously stutters back and forth. I cannot disable doDaylightCycle in the world since I have other arenas for PVP in that world -- which having a full daylight cycle adds to dynamic gameplay variation.

**Comment by garbagemule** [comment]
This has to be a plugin conflict or a Paper issue. On a completely barebones Spigot setup, zombies and skeletons never catch on fire and spiders attack as expected.
