### ISSUE TITLE
Can't join Arena Even Though It's Complete

### ISSUE THREAD

**Issue by nightdoom2003** [garbagemule/MobArena#526]
I created a new arena, but for some reason it won't let me join the arena under any circumstance.
Whenever I try, it claims that the arena hasn't been set up. But both the config and /ma checkdata and typing "missing" during setup all say that the arena is ready to go.
All arenas in the world have been enabled.
Why is this happening?

**Comment by garbagemule** [comment]
Please join Discord for support questions :)
