### ISSUE TITLE
Pillager is not attacking player

### ISSUE THREAD

**Issue by myfbone** [garbagemule/MobArena#531]
# Bug report

**Short description**

When I join the arena, pillagers spawned but were not attacking player. Just idling.

**Reproduction steps**
Add waves with pillagers

**Details**

* **MobArena version**: latest 
* **Server version**: Spigot 1.14

**Additional info**
I don't know, but I used crossbow during the game

**Comment by garbagemule** [comment]
Thanks for the report. 

This is likely a problem with Spigot not having implemented the targeting logic yet. Either way it's not something we can do anything about in MobArena. Best bet is to wait for fixes upstream.
