### ISSUE TITLE
Please add disable no item drops on arena

### ISSUE THREAD

**Issue by andris155** [garbagemule/MobArena#532]
# Feature request

**Short description**

Please add disable no item drops on arena

**Implementation details**

Add config option control this.
The no item drop cause item dupe if use /minecraft:give command.

**Additional info**

**Comment by garbagemule** [comment]
`share-items-in-arena`?

**Comment by andris155** [comment]
This setting is true on all arena. But item drop not work on the arena area. Example lobby, spectate location etc...

**Comment by garbagemule** [comment]
I don't understand what you mean. There's zero context in your description. What does /minecraft:give have to do with anything? When are you typing it and why? What do you mean by item dupe?

**Comment by andris155** [comment]
Players use shop on the mobarena area. The shop use /minecraft:give commands. The /minecraft:give command dupe items if player stand item drops protected area.

**Comment by SaitDev** [comment]
This is a known issue, but not from mob arena https://hub.spigotmc.org/jira/browse/SPIGOT-2942
You can use https://www.spigotmc.org/resources/essentialsx.9089/ with command `/essentials:give`
probably disable essential's commands from player if you dont want them

**Comment by andris155** [comment]
The EssentialsX give not support Attributes.

**Comment by SaitDev** [comment]
yea not support...
can you check if you have any else area protect plugin like world guard or similar?

**Comment by andris155** [comment]
Yes, arenas protected with the WorldGaurd.
And same problem if enabled nodrop flag.

**Comment by SaitDev** [comment]
Unfortunately, since this is an issus exists in spigot itself, we dont have much thing to fix it ourself.
For me Im using denizen plugin so Im glad to use it to write custom script that give player items with attributes. https://www.spigotmc.org/resources/denizen.21039/
If you dont wanna use denizen, hope u can find another solution

**Comment by garbagemule** [comment]
Let's hope md_5 takes the issue a bit more seriously so it can be fixed at the source rather than having to come up with random workarounds in every plugin that blocks a drop event.
