### ISSUE TITLE
Custom Bosses

### ISSUE THREAD

**Issue by Fr0sto** [garbagemule/MobArena#533]
# Feature request

**Short description**

Server owners should have a way to use custom bosses from other plugins, like Boss (by Kangarko), MythicMobs, EpicBosses (by Songoda, available at songoda.com), etc. This would make boss waves and even other types of waves MUCH more customizable and interesting.

**Implementation details**

When configuring your waves, you would just insert a custom mob by specifying which plugin it came from and then noting its name (as configured with the separate boss plugin). Small example below.

def1:
    type: default
    priority: 1
    frequency: 1
    monsters:
        Boss:SuperZombie: 10
        MythicMobs:FlyingCreeper: 4
         exploding_sheep: 5

**Comment by garbagemule** [comment]
This is possible via Sait's extension plugin: https://github.com/SaitDev/MobArenaExtension
