### ISSUE TITLE
Signs don't work after upgrading and cannot find info for class signs

### ISSUE THREAD

**Issue by Klawdek** [garbagemule/MobArena#535]
# Documentation

**Description**

After upgrading my server from 1.12.2 to 1.13.2 and Mob Arena from 0.103 to 0.103.2 all signs stopped working.  Deleting and redoing them seems to work.  However I was unable to find any info on how to do the class picking signs and I don't remember how it was done.  

Please put the info for how to make class signs I have tried a bunch of things and cannot get it to work.

**Additional info**

**Comment by Nesseley** [comment]
The class picking signs is the name of the class on the top line of the sign, please join the discord for more support :)

**Comment by Klawdek** [comment]
Thank you I finally figured that out.  It wasn't working at first but after a few config reloads and enabling and disable mobarena the class signs I had and the new one I had made started working. Thank you for your response.

**Comment by garbagemule** [comment]
It's right here :)

https://github.com/garbagemule/MobArena/wiki/Arena-Setup#building-an-arena
