### ISSUE TITLE
Wither Skeletons should have swords

### ISSUE THREAD

**Issue by Fr0sto** [garbagemule/MobArena#538]
# Feature request

**Short description**

Wither skeletons spawned through wave configurations should, by default, hold stone swords. It seems as though they do spawn with them sometimes, but they certainly do not all of the time. Maybe it's based on the type of wave that they spawn from currently, I'm not sure.

**Implementation details**

Although this particular request is purely for wither skeletons, depending on how it was implemented it could potentially add a way to customize all wave mobs' armor and hand-items.

**Comment by Nesseley** [comment]
Hey! 
We tried fixing this bug in the jam today, and we have a build in discord for you to test! :)

You can find it in the #test-builds chat.
Please let us know if this fixed your problem.
