### ISSUE TITLE
Water potions cannot be granted through waves

### ISSUE THREAD

**Issue by Fr0sto** [garbagemule/MobArena#540]
# Bug report

**Short description**

For example, when I use a wave configured like this:
`single:
        upgrade1:
          type: upgrade
          wave: 3
          upgrades:
            all: potion:instant_heal:2, potion:water`
the player does not recieve a water bottle, but instead gets an uncraftable pink potion. This is in error because a water bottle is technically a potion which has a type of water (The give command for a water bottle is /give @p minecraft:potion{Potion:"minecraft:water"} 1), and there is otherwise no way to give water bottles to players through waves.

**Reproduction steps**

1. Attempt to give arena participants a water bottle through wave configurations
2. Inevitably fail

**Details**

* **MobArena version**: 0.103.2
* **Server version**: PaperMC Build 80, 1.14.2

**Additional info**

The reason this is important to me is that my arena is nether-based (lots of lava traps), and water bottles on my server extinguish the player when consumed.

**Comment by Nesseley** [comment]
You need to define how many water bottles you want. 
`potion:water:1` works. :)

**Comment by Fr0sto** [comment]
Ah, thank you!!!!
