### ISSUE TITLE
When a player dies the server shuts down

### ISSUE THREAD

**Issue by Laxider** [garbagemule/MobArena#541]
As soon as the plugin is installed, the server is restarted and everything is started normally, any player that dies, regardless of being killed, the server freezes for 10 seconds and then shuts down.
IN VERSION: 1.13.2 BUKKIT
(PD: sorry, my english is very basic, y use GoogleTraslator)

**Comment by garbagemule** [comment]
I don't think this is a MobArena-only issue - if it was, we'd see many, many more bug reports like this one. You're in a unique position to figure out which plugin might be interfering. As long as this doesn't happen on a brand new Spigot build with nothing but MobArena installed, it's hard to do anything about it.

**Comment by garbagemule** [comment]
@Laxider do you have any new information on this? Any clues as to what might be causing it? I haven't heard anyone else experience this.
