### ISSUE TITLE
Signs will not work if placed on walls  [1.14.3 Paper]

### ISSUE THREAD

**Issue by WavingStory** [garbagemule/MobArena#546]
# Bug report

**Short description**

When placing any kind of sign on a wall, the sign will simply not work. It will only work when placed on the ground.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Nothing happens, you may get an error in console such as "org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign" for custom class chests.

**Details**

* **MobArena version**: 0.103.2
* **Server version**: Paper 131 (1.14.3)
* **Stacktrace** (if applicable): org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign (ClassChests:45)

**Additional info**

**Comment by garbagemule** [comment]
Thanks for the bug report!

It appears to be a problem with breaking API changes in Spigot. The MaterialData API is deprecated, and I think it has finally been removed/disabled/whatever.

I came across this issue in a Google journey, which hints that it is indeed just wall signs: https://github.com/NLthijs48/AreaShop/issues/502

Here's a clue as to how to solve it: https://www.spigotmc.org/threads/getting-block-behind-sign-in-1-14.370340/

Might be a good excuse to weed through some of the deprecated API that MobArena uses and clean things up a bit.

**Comment by Nesseley** [comment]
Hey! 
We tried fixing this bug in the jam today, and we have a build in discord for you to test! :)

You can find it in the #jam chat and i've pinned it for you.
Please let us know if this fixed your problem.

**Comment by Nesseley** [comment]
Hey! 
We tried fixing this bug in the jam today, and we have a build in discord for you to test! :)

You can find it in the #jam chat and i've pinned it for you.
Please let us know if this fixed your problem.
