### ISSUE TITLE
Iron Golems don't do damage to aggressive mobs

### ISSUE THREAD

**Issue by Azurda-X** [garbagemule/MobArena#550]
# Bug report

**Short description**

Iron golems do not damage aggressive mobs in mob arena.
They will aggro, but not damage them. This changes if monster infighting
is on, but then any mob can damage each other.

**Reproduction steps**

1. join arena
2. spawn iron golem
3. have enemies
4. golems doesn't deal damage but aggro them

**Details**

* **MobArena version**: n/a
* **Server version**: n/a

**Additional info**
Provided link:
https://github.com/garbagemule/MobArena/blob/cd1f7ff797b320a8e87a367e39e6de4bd5f8654f/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L823

**Comment by garbagemule** [comment]
Thanks for the bug report!

Just to be clear, when you say "spawn iron golem", you mean build an iron golem manually in the arena with iron blocks and a pumpkin, right?

It looks like what's happening is that MobArena "guesses" that the golem is actually not a friendly golem but a hostile mob, so it defaults to the rules of "mob vs. mob", which is cancelled unless monster infighting is on.

The fix here is likely a matter of introducing a check to see if the "damager" is a player-made golem, and if it is, allow the damage to pass through uncancelled.

**Comment by Azurda-X** [comment]
Golems don't deal damage whether there built, or a custom enchantment spawns them in/
