### ISSUE TITLE
Cmd outside reward waves.

### ISSUE THREAD

**Issue by Azurda-X** [garbagemule/MobArena#551]
# Documentation

**Description**
Cmd command works outside of rewards, however the documentation is lacking, and hasn't been upgraded sence the feature was added (https://github.com/garbagemule/MobArena/issues/468) however, the lack of documentation means this is confusing as others don't know that this has been implemented. Causing more posts like these. 

Simply add what other rounds cmd can work in, as well as examples as to what commands will and won't work if not stated already.

**Comment by garbagemule** [comment]
Thanks for the suggestion to update the documentation!

When the feature in question was implemented, the documentation was updated along with it. The Item and Reward Syntax page, which explains how the syntax for items, rewards, etc. works explains how to use commands as things.

Could you give an actual example of how the documentation should be updated and where? There is no context in your description.

**Comment by Azurda-X** [comment]
The doccumention only states that commands are rewards. Ex the section. "Command Rewards" as well as the following statement. "Since v0.99, MobArena supports commands as rewards."  No where in the The Item and Reward Syntax page does it state that cmds can be used for outside rewards.

As for an example:
Commands
Since (whatever ver commands were fully fleshed out into waves), MobArena supports use of commands in supply and upgrade waves. As well as rewards. This means that you can have the server run a command that targets the recipient player. This is useful for granting persistent permissions via your permissions plugin, commands to supply and upgrade, and grant permissions or effects from other plugins. The basic syntax is this:

cmd:/give <player> dirt
If the player is "garbagemule", this setting will run the command "/give garbagemule dirt" on the wave it is specified, via upgrade/supply or in rewards. In upgrade and supply waves. The command will simply be run, but in reward waves. The syntax will display as [MobArena] You just earned a reward: /give <player> dirt, which isn't very pretty. If you want the reward to have a title, simply expand the cmd with the name in a parenthesis:

*cmd(a very nice thing):/give <player> dirt
This will display as [MobArena] You just earned a reward: a very nice thing

*Name will only appear in the rewards section.

**Comment by Nesseley** [comment]
I suggest that Item and Reward Syntax page should state that some of it can only be used in the "Rewards:" and "Upgrades:" section of the waves. This isn't clearly stated anywhere, and I see how some people could miss this.

**Comment by garbagemule** [comment]
I have rewritten the entire page now.

@Nesseley will you give it a look when you have time?

**Comment by Nesseley** [comment]
The enchantment part is missing how to enchant a book. But otherwise it looks good.

**Comment by garbagemule** [comment]
Wiki has been updated.
