### ISSUE TITLE
lock-food-level:true affects all players server wide.

### ISSUE THREAD

**Issue by selfslaughter** [garbagemule/MobArena#557]
# Bug report

**Short description**

**lock-food-level:true** - Locks all players hunger bars once an arena has started. Not just players participating in the given arena. Making it impossible for other users to get hungry or unable to eat and refill their hunger bar while a mobarena match is in progress.

**Reproduction steps**

1. Set lock-food-level:true
2. Start starving to death
3. Have another player begin a mobarena match
4. Try to eat
5. Die

**Details**

* **MobArena version**: 0.103.3-SNAPSHOT (md5: 2cf3f39c1b9bea7b24e5c0880d2f3e01)
* **Server version**: Paper 1.14.4 (Build 147)

**Additional info**

**Comment by garbagemule** [comment]
Thanks for the bug report!

It looks like this was introduced in 88ddbe5ac6ac5aa0f18ade50aa376b25546fb058, so it hasn't yet been released (no need to modify the changelog), fortunately :)
