### ISSUE TITLE
Mythic Mobs Not Spawning

### ISSUE THREAD

**Issue by MooshroomStatus** [garbagemule/MobArena#559]
When using Mythic Mobs as the monsters I want in my arena, only 1 mob fully spawns. The rest spawn too but then get removed instantly. After killing the one that still exists, the arena wave freezes due to others being removed.

1. Do the basic arena setup as normal
2. Change the recurring waves to include only mythic mobs as listed monster types
3. Join the arena and attempt to play. Only one mob will spawn and the wave will freeze.

MA Version: 0.103.2
MA Sait Extension: Latest
Server Version: 1.13.2

Allowing other mobs to be spawned in the arena would be nice as well for the sake of animations, boss fights with minions, etc.

**Comment by Nesseley** [comment]
Can you send your config in a pastehin/hastebin? :)

**Comment by MooshroomStatus** [comment]
Yeah I can:
https://pastebin.com/k1cf45km

**Comment by Nesseley** [comment]
What happens if you also spawn regular zombies in the same default wave?

**Comment by MooshroomStatus** [comment]
If I switch it to any normal mob, the exact amount of them still spawn. Only mythic mobs spawn one at a time

**Comment by Nesseley** [comment]
Thats weird, If you join our discord maybe someone with a little more mythic mob experience can help. I've never really used that plugin. Sait is also in the discord. :)

**Comment by MooshroomStatus** [comment]
I can try. I'll probably get redirected to this though

**Comment by garbagemule** [comment]
Sorry for being a bit of a buzz kill here, but if normal mobs work just fine, this is not a MobArena issue, so this issue doesn't belong here.
