### ISSUE TITLE
Setting-up-the-waves#upgrade-waves does not show how to give effects.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#560]
# Documentation

**Description**
The page Setting-up-the-waves#upgrade-waves is missing an example on how to give out effects in the config file for upgrade waves. It states `Upgrade Waves can be set up to upgrade/replace armor, as well as add/replace potion effects and add/remove permissions` but it only shows armour, items and permissions.

**Additional info**
Probably not.

_Edited because of a copy paste error._

**Comment by garbagemule** [comment]
Fixed: https://github.com/garbagemule/MobArena/wiki/Setting-up-the-waves#upgrade-waves
