### ISSUE TITLE
Evoker bug

### ISSUE THREAD

**Issue by the-red-soul** [garbagemule/MobArena#564]
Description:

1. If you use any of the Evoker mob in MA and they summon their Vexes, if the arena ends the Vexes do not immediately despawn and still "float" around. Finally dying normally after the set expiration time.

Its very easy to replicate. Just have some Evokers in a normal wave, and let them create their Vex's, then die in MA. you will find that they do not despawn.

**Comment by garbagemule** [comment]
Thanks for the bug report!

It's likely due to vexes not being "registered" by MobArena when they spawn. I seem to recall that they just didn't spawn at all at some point, but I guess now we have the opposite problem. I'll take a stab at it and see what I can come up with.
