### ISSUE TITLE
Error when MobArena enable

### ISSUE THREAD

**Issue by FoviOX** [garbagemule/MobArena#569]
**Short description**
When MobArena enable, appear error. MobArena starting faster than all worlds

**Reproduction steps**
3. Error appears in console

**Details**
Error https://pastebin.com/64YsCpxD

* **MobArena version**: 0.104
* **Server version**: PaperSpigot 1.12.2

**Additional info**
This error appear not only in Paper, in default Spigot too.

**Comment by garbagemule** [comment]
Please use Discord for support questions. 

Looks like your config file references a world that no longer exists. Do a find/replace and you should be good to go. If not, hop on Discord for help.
