### ISSUE TITLE
Items not recognised

### ISSUE THREAD

**Issue by phoenix1238** [garbagemule/MobArena#570]
Some of the items are not recognised.

For example, acacia sapling, red rose etc etc

So for acacia sapling, the material id is 6 and the data is 4

So according to the wiki, in the classes to receive I put 6:4:1. I get an error msg 

'Failed to parse item for class <class>: <whatever I enter, such as 6:4:1>

This problem extends to red_rose and many others. I have tried other variations, such as:
- sapling:4:1
- sapling:acacia:1
- acacia_sapling
- "6:4:1"
- 6:4

**Comment by Nesseley** [comment]
Hey! Please use the template when reporting bugs! Also join our Discord for support :)

**Comment by cbronak** [comment]
Numbers are no longer repesenting item-IDs and some ids change with every update.
Here is a full item list for 1.14 https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

Your "red_flower" is now "poppy" and "acaia_sapling" should work.

**Comment by garbagemule** [comment]
Thanks @cbronak!

**Comment by phoenix1238** [comment]
Those were examples of items. There are many, many more such almost all
non-block items which are variations of a set block e.g (this is an example
but works) having a variation of stone as 1:1 as opposed to 1:0, but only
applying to other non-block items. Dyes seem to be the only ones that work
when this was tested. Thing like Charcoal do not, including coal:1 or
'charcoal'
