### ISSUE TITLE
Phantoms attack players in arenas.

### ISSUE THREAD

**Issue by Klawdek** [garbagemule/MobArena#572]
# Bug report

**Short description**

Phantoms are attacking players in arenas that have open tops

**Reproduction steps**

Make an arena with no roof.  wait until night.  Have players join arena where at least one has not slept in bed for three minecraft days.

Non console errors on this just unexpected behavior.

**Details**

None needed for this one.
* **MobArena version**: 0.104
* **Server version**: Paper version git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Additional info**

I know the phantoms can be despawned when flying into the arena area.  Towny does it with all mobs that enter an area that disallows mobs.  It would be a good idea to put that into mob arena as having to deal with unwanted phantoms is causing player complaints. Rebuilding all arenas and being required to build all future arenas with roofs is limiting of design.

**Comment by Nesseley** [comment]
For now you can use barrier blocks at the top of your arena to prevent this.

**Comment by Klawdek** [comment]
Yes I know.  Those are a pin to work with.  Since my arenas are all in a separate world that is just for arenas and event areas and I am using world guard, I changed the __global__ region to disallow phantom spawns.  However it would be nice to see this feature added at some point.  It would make the plugin more stand alone with less need for outside solutions.

**Comment by garbagemule** [comment]
Thanks for the bug report!

It actually looks like _any_ monster outside of MobArena can potentially target arena players, which shouldn't really be the case. @Klawdek, could I get you to test this out by spawning a monster somewhere near an arena and see if a player inside the arena will aggro it?
