### ISSUE TITLE
Spawn mobs 

### ISSUE THREAD

**Issue by wallxq** [garbagemule/MobArena#574]
Hi! How i can turn on monster spawning? Because now is cancelled to prevent pollution. Its problem for me becasue i want do "help" by golems for players. I cant get signs with "mobspawn" for money on the arena.

**Comment by garbagemule** [comment]
Hiya,

Please use Discord for support questions :)

MobArena doesn't allow spawning other mobs than the ones it is in charge of. Iron golems built in the arena with iron blocks and pumpkin heads _are_ supported though.
