### ISSUE TITLE
message spam

### ISSUE THREAD

**Issue by PhanaticD** [garbagemule/MobArena#575]
just set up a basic arena, tested it out for first time and died and this spammed: https://gyazo.com/f091d111f1162625bd983624271ff2a3

im on 1.8.8 server
 MobArena version 0.104

**Comment by Nesseley** [comment]
Your gyazo has an error so we can't view it

**Comment by garbagemule** [comment]
Please hop on Discord for support questions :)

Looks like MobArena gets stuck in a warp loop because you have conflicting plugins or regions.
