### ISSUE TITLE
Potion Effects Not working in 1.12

### ISSUE THREAD

**Issue by Beanzilla** [garbagemule/MobArena#576]
# Bug report

**Short description**

I have edited the default classes to add Strength to class Knight, but on start up I see in the server logs:
`Failed to parse potion effect of class Knight: effect:STRENGTH`

I have tried using:
* `effects: strength`
* `effects: Strength`
* `effects: effect:strength`
* `effects: effect:STRENGTH`

**Reproduction steps**

1. Create a new class
2. add `effects: strength`
3. start server and look at server logs

**Details**

* **MobArena version**: 0.104
* **Server version**: This server is running Paper version git-Paper-1143 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
* **Stacktrace** (if applicable): NONE

**Additional info**

I have read the Items and Rewards Syntax on the wiki but I still don't understand why it doesn't work.

**Comment by Nesseley** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html The wiki has a wrong link I think. But this is the right names for effects

**Comment by Beanzilla** [comment]
Ah, thanks... I think that will do it.
