### ISSUE TITLE
Integrating MobArena using JitPack failing due to bStats

### ISSUE THREAD

**Issue by TheSteveRizzo** [garbagemule/MobArena#578]
Hi there,

I've reported this issue to bStats, initially, but I think I've found that the issue originates from the maven dependencies in the MobArena pom file, instead. I'm not quite sure, as this is the first time attempting to use JitPack integration, however the following error reports when packaging the project:

> Failed to collect dependencies at com.github.garbagemule:MobArena:jar:0.103.2 -> org.bstats:bstats-bukkit:jar:1.2: Failed to read artifact descriptor for org.bstats:bstats-bukkit:jar:1.2: Could not transfer artifact org.bstats:bstats-bukkit:pom:1.2 from/to jitpack.io (https://jitpack.io): Not authorized -> [Help 1]

Has the Maven dependency for bStats been converted to the CodeMC repository (I only recently found out about this, myself, from the author), or is this error completely unrelated?

I truly appreciate any advice regarding this issue.

Best,
Steve

**Comment by garbagemule** [comment]
I haven't built the project in a few weeks, but there is a recent pull request that also changes the bStats repo. I'll look into it this weekend. Thanks for bringing it up :)

**Comment by TheSteveRizzo** [comment]
I appreciate it! I was going to make a pull request, but I figured it was already handled or being looked into. I'll go ahead and close this report. 

Thanks again.

**Comment by garbagemule** [comment]
All good! I'll leave the issue open to make sure I don't forget about it :P
