### ISSUE TITLE
failed to load config file

### ISSUE THREAD

**Issue by tacocoma** [garbagemule/MobArena#581]
# Bug report

**Short description**

When I setup my config the way that I want it, it will often reset itself and delete my changes when I reload the server or the plugin's config. I must be doing something wrong to the config.

**Reproduction steps**

I will paste my entire config below in the details.

**Details**

global-settings:
  enabled: true
  allowed-commands: /list, /pl
  update-notification: true
  prefix: '&a[MobArena] '
  pet-items:
    wolf: bone
classes:
  Knight:
    items: diamond_sword, potion:instant_heal:3
    armor: iron_helmet, iron_chestplate, iron_leggings, iron_boots
  Tank:
    items: iron_sword, potion:instant_heal:2
    armor: diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots
    effects: slow, health_boost
  Archer:
    items: wooden_sword, bow, arrow:256, potion:instant_heal:3, bone
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
    effects: speed
  Chemist:
    items: stone_sword, splash_potion:instant_damage:30, splash_potion:poison:8, splash_potion:instant_heal:20,
      potion:instant_heal:3
    armor: chainmail_helmet, chainmail_chestplate, chainmail_leggings, chainmail_boots
    effects: speed:1
  Oddjob:
    items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:instant_heal:3
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
arenas:
  default:
    settings:
      prefix: ''
      world: world
      enabled: true
      protect: true
      entry-fee: ''
      default-class: 'myitems'
      clear-wave-before-next: true
      clear-boss-before-next: true
      clear-wave-before-boss: true
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      share-items-in-arena: true
      min-players: 1
      max-players: 10
      max-join-distance: 0
      join-interrupt-timer: 3
      first-wave-delay: 15
      next-wave-delay: 5
      wave-interval: 15
      final-wave: 50
      monster-limit: 50
      monster-exp: true
      keep-exp: true
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: true
      auto-start-timer: 60
      start-delay-timer: 60
      auto-ready: false
      use-class-chests: false
      boss-health-bar: boss-bar
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: true
      global-end-announce: true
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            enderman: 10
          growth: medium
        def2:
          type: default
          priority: 2
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            enderman: 10
          growth: medium
          health-interval:2
          wave: 10
        def3:
          type: default
          priority: 3
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            enderman: 10
          growth: medium
          health-interval:3
          wave: 20
        def4:
          type: default
          priority: 4
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            enderman: 10
          growth: medium
          health-interval:4
          wave: 30
        def5:
          type: default
          priority: 5
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            enderman: 10
          growth: medium
          health-interval:5
          wave: 40
        spec1:
          type: special
          priority: 6
          frequency: 5
          monsters:
            powered-creepers: 1
            zombie-pigmen: 5
            blazes: 3
      single:
        boss1:
          type: boss
          wave: 25
          monster: wither_skeleton
          name: &6&lSkeleton Boss
          health: medium
          reward: 1500
          drops: diamond
          abilities: arrows, fireballs, obsidian-bomb, root-target, warp-to-player, throw-nearby
          ability-announce: true
          ability-interval: 8
          effects: speed:3:1000, increase_damage:2
        boss2:
          type: boss
          wave: 50
          monster: wither
          name: &6&lWither Boss
          health: high
          reward: 2500
          drops: diamond_block
          abilities: arrows, fireballs, obsidian-bomb, root-target, warp-to-player, throw-nearby, fire-aura
          ability-announce: true
          ability-interval: 8
          effects: speed:5:1000, increase_damage:2
    rewards:
      waves:
        every:
          '5': 50
          '10': 250
        after:
          '25': 1000
          '50': 2500
    coords:
      spawnpoints:
        17912,197,11403: 17912.5,197,11403.5,0.0,0.0,world
        17927,197,11403: 17927.5,197,11403.5,0.0,0.0,world
        17927,197,11417: 17927.5,197,11417.5,0.0,0.0,world
        17912,197,11417: 17912.5,197,11417.5,0.0,0.0,world
        17940,194,11427: 17940.5,194,11427.5,0.0,0.0,world
        17937,194,11430: 17937.5,194,11430.5,0.0,0.0,world
        17902,194,11430: 17902.5,194,11430.5,0.0,0.0,world
        17899,194,11427: 17899.5,194,11427.5,0.0,0.0,world
        17899,194,11393: 17899.5,194,11393.5,0.0,0.0,world
        17902,194,11390: 17902.5,194,11390.5,0.0,0.0,world
        17937,194,11390: 17937.5,194,11390.5,0.0,0.0,world
        17940,194,11393: 17940.5,194,11393.5,0.0,0.0,world
        17941,194,11410: 17941.5,194,11410.5,0.0,0.0,world
        17919,194,11431: 17919.5,194,11431.5,0.0,0.0,world
        17898,194,11410: 17898.5,194,11410.5,0.0,0.0,world
        17920,194,11389: 17920.5,194,11389.5,0.0,0.0,world
      containers:
        17914,194,11390: 17914,194,11390,0.0,0.0,world
        17925,194,11430: 17925,194,11430,0.0,0.0,world
      p1: 17893,0,11366,0.0,0.0,world
      p2: 17949,227,11457,0.0,0.0,world
      arena: 17919.5,194,11410.5,-91.05,0.0,world
      lobby: 17920.5,234,11409.5,0.15,0.0,world
      spectator: 17920.5,230,11410.5,-1.95,0.0,world
    class-limits:
      Oddjob: -1
      Knight: -1
      Archer: -1
      My Items: -1
      Tank: -1
      Chemist: -1

**Additional info**

If you need the server version or anything else to test it please let me know. I can provide my server ip and operator commands for a dev if that works too.

**Comment by Nesseley** [comment]
Please join discord for support. 
And use hastebin to send configs :)

**Comment by tacocoma** [comment]
gotcha thanks!
