### ISSUE TITLE
Add abilities

### ISSUE THREAD

**Issue by Zelenium** [garbagemule/MobArena#588]
Good day. I apologize immediately for my English. I’m here recently engaged in the refinement of your plugin. Already succeeded in several things, for example, made it possible to spawn several bosses in 1 wave. Today I decided to add new abilities to bosses and found that you turned on the option to add boss abilities directly in the plugin folder. However, I, alas, did not find any documentation and rules on how to do this. Can you help me with this?

**Comment by garbagemule** [comment]
Hiya! The custom abilities are a bit of a "hidden" feature nowadays. You just place the Java source files in the `MobArena/abilities/src` folder and make sure to follow the same code structure as the core abilities, which are available in the repo.

Hop on Discord for more info :)

**Comment by Zelenium** [comment]
Thank you!
