### ISSUE TITLE
Rewards config file

### ISSUE THREAD

**Issue by blackbar0n** [garbagemule/MobArena#600]
Hi,

I'm not able to change the items for the rewards.
I know the config file is good because I can change the kits items but I fell like the rewards are hardcoded in the MobArena-master/src/res/rewards.yml .

Am I right ?
Bk

**Comment by garbagemule** [comment]
Hiya!

Rewards are not hardcoded, no. Check the Item and Rewards Syntax page on the wiki.

Please hop on Discord for additional support :)
