### ISSUE TITLE
Improve arena signs documentation

### ISSUE THREAD

**Issue by Bobcat00** [garbagemule/MobArena#603]
# Documentation

**Description**

When I first started looking at the use of arena signs, I had some difficulty understanding a key concept. Although technically accurate, the documentation doesn't adequately explain the difference between \<type\> and \<template\>, on the third and fourth lines of the signs, respectively.  The confusion is increased in that template inherits its value from the type, even though they mean entirely different things.

I suggest adding an additional section in the documentation before the Templates section:

Sign Types

The third line of the sign is the sign type: join, leave, or info.  This specifies what happens when the player interacts with the sign (e.g., clicks on it).  Join and leave signs will cause the player to join or leave the arena.  Info signs will do nothing when the player interacts with them.

Note that all three types of signs can display the same types of information.  Join and leave signs can display the same types of information that info signs can display.

The actual information displayed on a sign is defined by the sign template, which can be predefined or user-defined.

(This then leads into the Templates documentation)

**Comment by garbagemule** [comment]
Thanks for the input. I took it and ran with it, so the Arena Signs page has gone through a bit of a rework. Is it improved sufficiently for this issue to be closed? :)

**Comment by garbagemule** [comment]
Gonna go ahead and close this one. If we need to improve the documentation further, please reopen :)
