### ISSUE TITLE
Run command on class select

### ISSUE THREAD

**Issue by zer0key123** [garbagemule/MobArena#617]
# Feature request

**Short description**

Similar to wave rewards able to be set as commands, allow classes to run commands when they get selected(and probably deselected as well)

**Implementation details**

Add 2 additional optional parameters under each class in `classes`, one being `select_cmd` and the other - `deselect_cmd`; `select_cmd` would be the command ran when the class is selected, and `deselect_cmd` the one when its deselected.

**Comment by garbagemule** [comment]
Gonna close this as this is technically possible with command items.

If it's still relevant, feel free to reopen.
