### ISSUE TITLE
player-time-in-arena doesn't work

### ISSUE THREAD

**Issue by Bobcat00** [garbagemule/MobArena#621]
# Bug report

**Short description**

Arena config has `player-time-in-arena: midnight` but the time in the arena is the same as the normal world time.

**Reproduction steps**

Set world's time to day
Set `player-time-in-arena: midnight`
Join arena
Start game

**Details**

* **MobArena version**: 0.104.3-SNAPSHOT
* **Server version**: git-Spigot-2f5d615-d07a78b (MC: 1.15.2)
* **Stacktrace** (if applicable): N/A

**Additional info**

garbagemule is a steely-eyed missile man.

**Comment by Bobcat00** [comment]
The Essentials ptime command works, so it would seem this is a problem with MobArena.

**Comment by Bobcat00** [comment]
This line needs to be `toUpperCase()`
https://github.com/garbagemule/MobArena/blob/58cb29ae975f343750f91936c4442e260f5cd7b0/src/main/java/com/garbagemule/MobArena/steps/SetPlayerTime.java#L37

**Comment by Chew** [comment]
![image](https://user-images.githubusercontent.com/8278263/82133781-779eec00-97b5-11ea-81d8-4265ce3d2914.png)
