### ISSUE TITLE
How to use a separate scoreboard plugin such as featherboard for the Arena.

### ISSUE THREAD

**Issue by B1022** [garbagemule/MobArena#625]
Hey! How can I use a separate plugin such as feather board to change the scoreboard during arenas? Any Ideas? Thanks!

**Comment by Chew** [comment]
There would have to be placeholders exposed for FB to hook into, as far as I know there aren't

**Comment by B1022** [comment]
Are you able to add any or would I have to talk to the dev of featherboard

**Comment by Nesseley** [comment]
You would need to use this: https://github.com/SaitDev/MobArenaExtension
Note that some placeholders are broken. Please use Discord for support next time :)
