### ISSUE TITLE
[Feature] Random boss-rewards

### ISSUE THREAD

**Issue by Ghmmy** [garbagemule/MobArena#628]
# Feature request

**Short description**

Currently we can only add 1 boss-killer reward. What I would love to see is that we can, just like the wave-rewards, add multiple rewards to the boss-rewards-list where it would choose one from. This allows us to add more RNG-based rewards for the boss-killers.

**Implementation details**

This could be done by just adding commas behind the rewards, the same way it works for the wave rewards:
`reward: stone:10, money:3000, cmd(1 token):/tm give <player> 1, ....`

This shouldnt be extremely difficult to implement (I think), since its just the same as the wave-rewards, but for the boss-killer rather than after every x waves.

**Comment by garbagemule** [comment]
This should be possible to do without breaking any existing functionality, and there are lots of reference code to look at in terms of implementation. Pretty decent first issue if someone wants to take a stab at it.
