### ISSUE TITLE
MythicMobs Extension

### ISSUE THREAD

**Issue by xPaZzyy** [garbagemule/MobArena#631]
**Short description**

We should have a MobArena Extension plugin, made and maintained by GarbageMule.

**Implementation details**

It would allow for MythicMobs to spawn in the MobArena.

**Additional info**
Should load the Extension AFTER mobarena loads, unlike Sait's extension that loads before mobarena.

**Comment by garbagemule** [comment]
Arguably a duplicate of #362. The _how_ and the _who_ aren't so important.
