### ISSUE TITLE
Health not regenerating in mobarena

### ISSUE THREAD

**Issue by Poweringg** [garbagemule/MobArena#634]
# Bug report

**Short description**

1. )When player enters to mobarena via clicking on "ready" block health not regenerating.

2.) Netherite armor wont equip automatically like diamond. You can see this on video.

**Reproduction steps**

1. Join an arena with /ma join ....
2. Hit a sign to pick a class
3. click on ready block & go to arena
4. hit yourself (by mob or fall etc.)
5. health not regenerating.

Health regenerates normally in MobArena lobby, also if player is not in arena.

Console is without any errors or warns.

**Details**

server: PAPER, 161 1.16.1
MobArena: 0.104.2
My other plugins:

![image](https://user-images.githubusercontent.com/15527318/89448469-f756aa00-d757-11ea-95c1-58c36a165f42.png)

video: https://www.youtube.com/watch?v=Kir4N5xBdiU

my config.yml - https://pastebin.com/Jr52qXpp

**Comment by garbagemule** [comment]
Please use Discord for support :)

You have `food-regen: false` in your config-file. Check the Setting up the config-file page on the wiki to read about what each setting does.

**Comment by Poweringg** [comment]
Yes thanks, my bad, its solved! 

But what about that netherite armor?

**Comment by garbagemule** [comment]
Ah, sorry. This is why each issue should only address one thing. 

Please open a new issue for that. Someone mentioned it on Discord. It will work if you use class chests, but not the config-file (or it might be the other way around).
