### ISSUE TITLE
Unbreakable Weapons doesn't work correctly on Class-Chests classes.

### ISSUE THREAD

**Issue by PrinceOfIonia** [garbagemule/MobArena#637]
# Bug report

**Short description**

When you create a class-chest class, if you set `unbreakable-weapons:` to `false`, your weapons and Totems of Undying will still have the 'Unbreakable' tag and won't take any durability damage. (There may be other non-armor items effected by this)

**Reproduction steps**

1. Setup a class chest, either type works. (Global or Local)
2. Place weapons/undying-totems in the class chest
3. Set `unbreakable-weapons:` to `false` in the MobArena config
4. Play any arena with your new class.... and still have unbreakable weapons

* **MobArena version**: 0.104.2
* **Server version**: git-Paper-135 Running 1.16.1 (Also tested on Spigot version 9639cf7 running 1.16.1)

**Additional info**
If you place armor in a regular inventory slot instead of the armor slot in the class chest (aka the last 4 slots of the class chest), it will still be breakable and take normal damage.

Regular classes (classes that don't use class-chests) still work correctly with `unbreakable-weapons:` set to `false`.

**Comment by Nesseley** [comment]
Just adding in: Do we really want `flint and steel` to be unbreakable at all?

**Comment by garbagemule** [comment]
After a bit of digging, it looks like MobArena only clones certain slots - specifically the armor slots - in the class chests before making any modifications to them. This means that if the class chest has, at any point in time, been used with the `unbreakable-weapons` flag omitted or set to `true`, those items in the class chest will have been modified. Flipping the flag to `false` will result in MobArena _not_ modifying the items, which means if they had already been made unbreakable, they still are.

The fix should be to clone the class chest items before making any modifications, and then throwing the modified clones into the player inventory. I have a fix for this ready in the test builds channel on Discord in a bit.
