### ISSUE TITLE
Could not pass SpellCastEvent to MobArena

### ISSUE THREAD

**Issue by Tstorm89** [garbagemule/MobArena#644]
**Short description**

MagicSpells and MobArena interactions cause some glitches. Certain spells have "broken" since adding the MobArena plugin. Additionally, when a spell is cast, the error message: ERROR Could not pass event SpellCastEvent to MobArena v0.104.2 comes up. This is a server-wide issue since adding MobArena, not just occurring while in the arena.

**Reproduction steps**

1. Add MagicSpells plugin
2. Add MobArena plugin

**Details**

* **MobArena version**: 0.104.2
* **Server version**: Paper-197
* **Stacktrace** (if applicable): n/a

**Additional info**
18.09 13:28:45 [Server] ERROR Could not pass event SpellCastEvent to MobArena v0.104.2
18.09 13:28:45 [Server] INFO java.lang.NoSuchMethodError: com.nisovin.magicspells.events.SpellCastEvent.getCaster()Lorg/bukkit/entity/Player;
18.09 13:28:45 [Server] INFO at com.garbagemule.MobArena.listeners.MagicSpellsListener.onSpellCast(MagicSpellsListener.java:44) ~[?:?]
18.09 13:28:45 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor486.execute(Unknown Source) ~[?:?]
18.09 13:28:45 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.util.compat.EventUtil.call(EventUtil.java:14) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.Spell.preCast(Spell.java:768) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.Spell.cast(Spell.java:732) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.Spell.cast(Spell.java:722) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.listeners.CastListener.castSpell(CastListener.java:143) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.listeners.CastListener.onPlayerInteract(CastListener.java:72) ~[?:?]
18.09 13:28:45 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
18.09 13:28:45 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
18.09 13:28:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
18.09 13:28:45 [Server] INFO at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1109) ~[?:?]
18.09 13:28:45 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1946) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInArmAnimation.a(SourceFile:31) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInArmAnimation.a(SourceFile:9) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-197]
18.09 13:28:45 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by garbagemule** [comment]
This is because MagicSpells made breaking API changes in v4. Hop on Discord and grab the build from the #test-builds channel if you don't want to wait for a new release :)

Related: #609

**Comment by Tstorm89** [comment]
I really appreciate the help, and the test-build definitely cleared up the console! There is still one problem though, and that is the broken spells. One in particular, "explode" had been configured to prevent block damage. However, since adding MobArena this spell does in fact damage blocks anywhere outside the arena.
