### ISSUE TITLE
Mobs won't spawn

### ISSUE THREAD

**Issue by NovaSoup** [garbagemule/MobArena#652]
# Bug report

**Short description**

When I join the arena, the mobs won't spawn. It shows the text on the screen that says 'boss' and everything, but nothing will spawn and the waves will randomly pass by.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Go into arena
4. Error

**Details**

* **MobArena version**: 0.105 (1.16.4)
* **Server version**: Spigot 3.4.5
* **Stacktrace** (if applicable): https://pastebin.com/gB5qbcnr

**Additional info**

This is a Minehut server, but I have never had this issue before. I recently made another arena in the same place just with a different name, and I also recently downloaded a custom items plugin called Slimefun.

**Comment by garbagemule** [comment]
It sounds like you have a conflicting plugin removing mobs as MobArena spawns them. That's not something we can do anything about in MobArena. My guess is it's a WorldGuard thing. If you can't figure it out on your own, hop on Discord and we can maybe take a look at it.
