### ISSUE TITLE
[Enhancements] Auto-Leave & Leaderboards

### ISSUE THREAD

**Issue by riparoo** [garbagemule/MobArena#661]
# Feature requests

**Automatic Leave Game**
> **Short description**
> We should be able to toggle an automatic leave time in an arena.
>
> **Implementation details**
> Add  `auto-leave-timer` in the config settings just like `auto-start-timer` except the timer only starts after all players have died.
>
> **Additional info**
> Would be nice if it was an on screen countdown just like the `auto-start-timer` has.

**Leaderboard System**
> **Short description**
> Top 10 Leaderboards system.
> 
> **Implementation details**
> Have the commands to show "Longest Lasted - Top 10" and "Most Mob Kills(Per Game) - Top 10"
> Ex. "/ma top round", "/ma top kills"
> Similar to the Balance Top format for economy servers.
> 
> **Additional info**
> Would be nice to be able to get PlaceHolderAPI to hook for Holographic displays.

**Comment by garbagemule** [comment]
This needs to be split up into two separate issues.
