### ISSUE TITLE
Is this a MA error? WARN ✗ Config Error for Condition line 'ANY': Failed to load custom condition ANY

### ISSUE THREAD

**Issue by Klawdek** [garbagemule/MobArena#665]
# Bug report

**Short description**

I keep getting the following error in my console:
WARN ✗ Config Error for Condition line 'ANY': Failed to load custom condition ANY

It does not say what plugin.  I have gone through many plugins searching their configs for the words condition and ANY
And I can find nothing.
It usually happens spontaneously with no link to any actions.
Today it happened twice after players did mobarena commands.
So is this a MA issue?

When I join the arena, X doesn't work.

**Reproduction steps**

I have no idea.

**Details**

* **MobArena version**: 0.105
* **Server version**: git-Paper-443 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **Stacktrace** (if applicable): https://pastebin.com/gB5qbcnr

**Additional info**

**Comment by garbagemule** [comment]
It is not.

**Comment by Klawdek** [comment]
Thank you.  One down 40 to go.
