### ISSUE TITLE
Rewards disappear

### ISSUE THREAD

**Issue by fdk123** [garbagemule/MobArena#670]
# Bug report

**Short description**

When i leave the arena after my death with command /ma leave, i got the reward, bone fore example.
And, if i open chest, to save my loot, and take my items to equip, my reward (bone) disappear from my inventory.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. go to step with death and spect, 
4. /ma leave
5. go to chest
6. open chest

**Details**
Config file — default

* **MobArena version**: 0.105
* **Server version**: mohist 1.16.5-429

**Additional info**
Plugins: AutoSaveWorld, LuckPerms, SAML, GFly, EasyWhitelist, Vault, Ultimate_Economy, WorldEdit, EntityTrackerFixer, AdvancedTeleport, CraftBook, MobArena, ServerSigns, ChatEx, Jails, Crime

**Comment by garbagemule** [comment]
Thanks for the detailed bug report.

I can't reproduce this on a clean Spigot server with nothing but MobArena installed. My guess is that it's a server implementation bug, a plugin conflict, or a client-side bug. I've never heard of _mohist_, but if it behaves differently than Spigot or Paper, then it isn't supported by MobArena.

Feel free to re-open if the issue can be reproduced on a clean Spigot or Paper setup, and if so, please provide any additional information necessary to reproduce it, such as config-file and arena setup steps.
