### ISSUE TITLE
Issue with Upgrade Waves - Can't Parse an Upgrade

### ISSUE THREAD

**Issue by RajaBranco** [garbagemule/MobArena#680]
Description:

  I'm recreating an old server from the old CraftBukkit days on a new Paper server, and I've been setting up all the plugins I want, including this one.
  I've been going through all the config files and setting everything as I used to have and went smoothly, except when it came to the upgrades in the upgrade waves. All is written correctly and even have the same names typed before those lines in the config file, but it just keeps giving me these errors:

"Failed to parse upgrades for class all in wave upgrade1 of arena default: potion:strong_regeneration:2"

I tried to change that potion into something else like "arrow:50", and it would go and give me the same error on one of the next potions I have. The weird thing is that before that I have other potions and it didn't give me the error for those ones, sometimes even the same exact potion and amount.

I'll leave a screenshot of how my classes are setup and how my upgrade waves are setup (one of them is the remaining line of the last class).

Thanks in advance!

![MobArena Upgrade Waves 1](https://user-images.githubusercontent.com/87382440/125484271-5b625399-08d3-4f58-a9ad-251a9fddb22a.png)
![MobArena Upgrade Waves 2](https://user-images.githubusercontent.com/87382440/125484273-3ac3ad28-01a6-4954-b1c4-9c0a936ddb3a.png)
![MobArena Classes](https://user-images.githubusercontent.com/87382440/125483971-93c70bcd-5df7-4b29-8716-4adabd27f704.png)

MobArena Version: v0.106
Paper Server Version: paper-1.16.5-778

**Comment by garbagemule** [comment]
Doesn't look like "regeneration" is a valid potion type. Check out the links on the Item and Reward Syntax page on the wiki. They'll help you figure out what values to use.

If that doesn't work, feel free to hop on Discord for support.

**Comment by RajaBranco** [comment]
> Doesn't look like "regeneration" is a valid potion type. Check out the links on the Item and Reward Syntax page on the wiki. They'll help you figure out what values to use.
> 
> If that doesn't work, feel free to hop on Discord for support.

Thanks for the hasty reply!

I'll check those better tomorrow, but for what I remember seeing it supposedly was correct. The issue also appeared for swiftness (and, if I'm not mistaken, strength and poison, but would have to see again).

If I can't gets this fixed I'll go on Discord then, thanks!
