### ISSUE TITLE
Piglins/Brute Piglins vanish mid-wave when turning to Zombified Piglins

### ISSUE THREAD

**Issue by Maroon28** [garbagemule/MobArena#684]
# Bug report

**Short description**

Putting a `piglin` or a `brutepiglin` in the monsters section of any wave makes them vanish mid-wave. This is due to MC trying to convert the piglins into zombified piglins, so they just get despawned, but MA prevents any new creatures from spawning to fill in the gap. This bug is only present if the arena is in the overworld, and it works fine if the arena is set in the nether. 

**Reproduction steps**

1. Join an arena with /ma join
2. Make sure you have either `piglin` or `brutepiglin` in one of your waves (Or both!) 
3. Stay alive for about 20 seconds, the piglins will disappear. 

**Details**

* **MobArena version**: 0.106
* **Server version**: git-Purpur-1171 (MC: 1.16.5) 
* **Stacktrace** (if applicable): No errors in console.

**Additional info**
There may be an easy fix to this issue, which is through applying NBT data to the piglins when they spawn. `IsImmuneToZombification:1b` This seems to prevent them from being turned into anything, and they preserve their state. 

Video to showcase:  https://cdn.discordapp.com/attachments/703191811681681480/869691533782290532/Minecraft__1.16.5_-_Multiplayer_3rd-party_Server_2021-07-27_23-20-36.mp4

**Comment by garbagemule** [comment]
Thanks for the thorough bug report :)

I think the proposed solution of flagging the piglins as immune to zombification is much, much better than trying to somehow "respawn" the piglin after removal or something crazy like that. And luckily, even with the recent MACreature circus, the `piglin` and `piglinbrute` keys don't exist on versions prior to 1.16, so employing the Piglin and PiglinBrute interfaces in those cases shouldn't cause any problems whatsoever, yay!
