### ISSUE TITLE
Vindicators don't spawn with iron axes

### ISSUE THREAD

**Issue by Maroon28** [garbagemule/MobArena#686]
# Bug report

**Short description**

When putting vindicators in any of the waves, they don't spawn with iron axes in their main_hand, as they should

**Reproduction steps**

1. Join an arena with /ma join
2. Put vindicators in one of the waves
3. Vindicators attack with only their hands, no iron axes

**Details**

* **MobArena version**: 0.106
* **Server version**: git-Purpur-1171 (MC: 1.16.5)

**Comment by garbagemule** [comment]
Good catch. We already have pillagers missing their crossbows, so getting them all fixed in one fell swoop before next release would be great.
