### ISSUE TITLE
MobArena money rewards issue

### ISSUE THREAD

**Issue by Crabmate** [garbagemule/MobArena#688]
Hi! 

I'm currently using EssentialsX and Vault for my server and I wanted to set $ reward for different waves in my MobArena but I can't, i followed the official guideline on https://github.com/garbagemule/MobArena/wiki/Item-and-Reward-Syntax#economy-money but it doesn't work.  (I'm kinda new to minecraft plugins) If You have any idea how to solve that issue, please reply. 

Thanks!
Mate

Here's the config file 

global-settings:
  enabled: true
  allowed-commands: /list, /pl
  update-notification: true
  prefix: '&a[MobArena] '
  pet-items:
    wolf: bone
classes:
  Knight:
    items: diamond_sword sharpness:2, potion:instant_heal:4
    armor: iron_helmet, iron_chestplate, iron_leggings, iron_boots
  Tank:
    items: iron_sword knockback:1;sharpness:1, potion:instant_heal:8 , golden_apple:4 , apple:4
    armor: diamond_helmet, diamond_chestplate, diamond_leggings, diamond_boots
    effects: slow, health_boost
    classchest: 443,65,22,0.0,0.0,Crabiverse
  Archer:
    items: wooden_sword knockback:2, bow, arrow:256, potion:instant_heal:4, bone
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
    effects: speed
  Chemist:
    items: stone_sword knockback:1, splash_potion:instant_damage:30, splash_potion:poison:8, splash_potion:instant_heal:20,
      potion:instant_heal:3, apple:4
    armor: chainmail_helmet, chainmail_chestplate, chainmail_leggings, chainmail_boots
    effects: speed:1
  Oddjob:
    items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:instant_heal:3
    armor: leather_helmet, leather_chestplate, leather_leggings, leather_boots
arenas:
  default:
    settings:
      prefix: ''
      world: Crabiverse
      enabled: true
      protect: true
      entry-fee: ''
      default-class: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      join-interrupt-timer: 0
      first-wave-delay: 5
      next-wave-delay: 0
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: false
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: true
      arena-warp-offset: 0
      boss-health-bar: boss-bar
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      announcer-type: title
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone:2, stick, $50, iron_ingot:1
          '5': dirt:4, gravel:4, stone:4, $100, iron_ingot:5, gold_ingot:2
          '10': iron_ingot:10, gold_ingot:8, diamond:2
        after:
          '7': minecart, chest_minecart, obsidian:2, emerald:1
          '13': iron_sword knocback:1, iron_pickaxe unbreakable:2 , iron_shovel efficiency:1
          '16': diamond_sword sharpness:2, $750, emerald:3
    coords:
      spawnpoints: {}
      containers: {}
    class-limits:
      Oddjob: -1
      My Items: -1
      Knight: -1
      Archer: -1
      Tank: -1
      Chemist: -1
  arena:
    settings:
      prefix: ''
      world: Crabiverse
      enabled: true
      protect: true
      entry-fee: ''
      default-class: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      join-interrupt-timer: 0
      first-wave-delay: 5
      next-wave-delay: 0
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: false
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      arena-warp-offset: 0
      boss-health-bar: boss-bar
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      announcer-type: title
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, chest_minecart, furnace_minecart
          '13': iron_sword, iron_pickaxe, iron_shovel
          '16': diamond_sword
    coords:
      spawnpoints:
        417,68,27: 417.5,68,27.5,0.0,0.0,Crabiverse
        408,68,29: 408.5,68,29.5,0.0,0.0,Crabiverse
        394,68,27: 394.5,68,27.5,0.0,0.0,Crabiverse
        396,68,19: 396.5,68,19.5,0.0,0.0,Crabiverse
        406,68,11: 406.5,68,11.5,0.0,0.0,Crabiverse
        393,68,11: 393.5,68,11.5,0.0,0.0,Crabiverse
        378,68,23: 378.5,68,23.5,0.0,0.0,Crabiverse
        376,68,16: 376.5,68,16.5,0.0,0.0,Crabiverse
      containers: {}
      p1: 360,47,-6,0.0,0.0,Crabiverse
      p2: 447,95,42,0.0,0.0,Crabiverse
      lobby: 439.5,68,19.5,-266.23,0.0,Crabiverse
      spectator: 400.5,73,8.5,-0.14,0.0,Crabiverse
      exit: 400.5,73,32.5,-177.6,0.0,Crabiverse
      l1: 437,67,17,0.0,0.0,Crabiverse
      arena: 422.5,68,20.5,-271.47,0.0,Crabiverse
      l2: 443,73,22,0.0,0.0,Crabiverse
    class-limits:
      Oddjob: -1
      My Items: -1
      Knight: -1
      Archer: -1
      Tank: -1
      Chemist: -1

**Comment by Nesseley** [comment]
Hey! Please come join us in Discord for support!

Your problem is probably that you edited the rewards into wrong arena :)
