### ISSUE TITLE
Arena didn't end on last wave ._.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#690]
# Bug report

**Short description**
Never happened before, but the arena didn't end when it should. it didnt go on either, we just stood there..

Killed last boss wave10, then first error showed up. then another error when bluebear did /forlat (/ma leave)

**Reproduction steps**
I am not sure, I just need some help :D

**Details**

* **MobArena version**: 0.106.1-SNAPSHOT
* **Server version**: Paper version git-Paper-135 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 321dd1d)
* **Stacktrace**: https://pastebin.com/mGARxV4J

**Comment by garbagemule** [comment]
It looks like a `null` reward managed to sneak in somewhere. MobArena should either fail fast (throw an error when a null reward is added) or just ignore null rewards entirely to prevent this from happening. The arena did _try_ to end as it should, but the null reward broke the end procedure.

**Comment by garbagemule** [comment]
The root cause of this is #691, which has been fixed for the next release :)
