### ISSUE TITLE
Make End Crystals placeable everywhere

### ISSUE THREAD

**Issue by LeadedJester1** [garbagemule/MobArena#695]
# Feature request

**Short description**
Flaming arrows do not currently seem to be able to light placed TNT when shot from a bow and it does not seem possible to place end crystals. This would be useful for a demolitionist class or a class that uses a lot of explosives.

**Implementation details**
This would basically allow server owners to add the ability for players to ignite TNT with flaming arrows and place end crystals.

**Additional info**
When you try to place an end crystal in an arena while it is in session, it does not even briefly place the block before removing it. It just simply will not let you place it.

**Comment by Nesseley** [comment]
So, I tested this on 1.17.1 Paper.

Flaming arrows do not light TNT like they should.

You can place end crystals just fine, if you place them on obsidian or bedrock (like they are designed to in vanilla, you can only place them on these two blocks)

**Comment by garbagemule** [comment]
Are end crystals supposed to ignite TNT?

**Comment by Nesseley** [comment]
Explosions usually trigger TNT (creeper exploding). 

I tested in single player to be sure:
End Crystals should explode if they are hit with *any* bow. Flame not needed.
End Crystals do trigger TNT to explode.

**Comment by LeadedJester1** [comment]
The fact that end crystals need to be placed on bedrock or obsidian explains one of the issues, though flaming bows still don't seem to light TNT when TNT is hit with a flaming arrow.

**Comment by Nesseley** [comment]
Flaming arrows should light TNT, that should probably have been a bug report in its own :) 

So you want end crystals to be able to be placed anywhere? That might break some peoples setups (designated areas with bedrock/obsidian floors) and would most likely need a new setting in the config.

**Comment by Nesseley** [comment]
Removed TNT from this and made #696

**Comment by garbagemule** [comment]
I'm not sure we can do much about placing end crystals outside their vanilla requirements. But if it's possible, wouldn't this be something that could be solved by WorldGuard?

**Comment by LeadedJester1** [comment]
I'm not too concerned about the end crystals not being able to be placed anywhere since this is a vanilla mechanic, but the flaming arrows thing with tnt would be nice to have.

**Comment by garbagemule** [comment]
Let's close this issue and continue with the flaming arrow issue instead then :)
