### ISSUE TITLE
Leaving the arena area teleports to the exit instead of to the spectator spot

### ISSUE THREAD

**Issue by sepulzera** [garbagemule/MobArena#699]
# Bug report

**Short description**

When I get removed from the session by leaving the arena area, I get teleported to the exit instead of to the spectator spot.

**Reproduction steps**

1. Build an arena where players can accidentally leave the arena area, f. e. by falling through a hole.
2. Join an arena with /ma join.
3. Leave the arena area, f. e. by falling through a hole.
4. Respawn at the exit, and not at the spectator spot.

**Details**

* **MobArena version**: 0.106
* **Server version**: Paper 1.16.5-786

**Comment by garbagemule** [comment]
This is not a bug.

When players move out of bounds, it is considered "cheating", and so they are _kicked_ from the arena, i.e. they "leave" the arena, so if the exit warp is set, that's where they will get kicked to.

**Comment by sepulzera** [comment]
I understand your point, thanks for clarification!

Maybe it should be mentioned in the docs: If you are building an arena where players can die by falling out of, the arena area should cover the ground, too.
