### ISSUE TITLE
Dupe glitch due to inventory restore

### ISSUE THREAD

**Issue by antibitcoin** [garbagemule/MobArena#711]
# Feature request
Requesting option to stop the plugin from restoring inventory at all in case of my items, or at least a feature that prevents players from physically leaving the arena.
some players are able to clip trough walls using vclip or any other methods than dropping the items outside
after that they can just /ma leave and get back the original items ending up with 2 items of whatever.
Regards

**Short description**

We should have a way to do X with Y.

**Implementation details**

A per-arena setting could make Z configurable.

**Additional info**

**Comment by garbagemule** [comment]
MobArena is not an anti-cheat plugin. We have to assume that anti-cheat plugins will do a better job at fixing the underlying issue of _cheating_ than a workaround in a minigame plugin would. There is also the option of simply disabling My Items if you can't make it work on your server.

There _are_ good reasons for adding support for an inventory restoration flag (#552), but anti-cheat measures are _not_ one of them. I'm completely open to the idea of this kind of feature, but not for the reason presented here.
