### ISSUE TITLE
When use projectiles pet (like blaze) and stand in the line of fire, you will take damage.

### ISSUE THREAD

**Issue by KozzaX** [garbagemule/MobArena#712]
# Bug report

**Short description**

Hi ! As explained in discord i've noticed that projectile pets (like a blaze for exemple), harm the players and the mobs in the arena, is it possible to prevent the projectiles pet to harm the players ?

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class with a blaze_rod in it to make spawn a Blaze for example
3. click on iron block to start arena
4. play and enjoy your own mob hitting you with fire :')

**Details**

* **MobArena version**: 0.106
* **Server version**: PAPER 1.18.1
* **Stacktrace** (if applicable): NONE

**Additional info**

Here is my config-file : https://pastebin.com/kgLid9m3

Thanks for the help ! :)

**Comment by garbagemule** [comment]
Thanks for the bug report. I've just confirmed the issue on my end and I have a fix incoming in a few secs :)
