### ISSUE TITLE
Announcement system for Bungee/Velocity

### ISSUE THREAD

**Issue by AllieDragon** [garbagemule/MobArena#713]
# Announcement system for Bungee/Velocity

**Short description**

Implement a way to have the arena start and end message with Velocity/Bungee. This would make it so players would have a way to know when the mob arena is either about to start so they can jump on and play or they'll know it's over if they are waiting so they can play on other servers without either continually asking when it'll be done.

**Implementation details**

Have an option similar to the title and message one but a third flag being broadcast. This would send a /pb message instead of a normal chat message so people across servers would be able to see it. This would affect how the chat would work allowing everyone on your network to see it not just the players on the server Mob Arena is on!

**Additional info**
If you make it work with /pb it would work with both Bungee and Velocity with the streamline plugin both tend to use to be able to do things easily like global chats.

**Comment by garbagemule** [comment]
It doesn't sound like this is a request for a proxy announcement system, but rather a request for custom command execution (`/pb`) during certain MobArena-specific events. If that's the case, this is just a special case application of the feature requested in #678, in which case this is a duplicate for a feature request that currently has a functioning workaround. I'm gonna close this as a duplicate, but feel free to re-open if I missed something.
