### ISSUE TITLE
Add `tnt-fuse-time`

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#715]
# Feature request

We have `auto-ignite-tnt: true`, but TNT takes too much fuse time after being placed (~2-4 seconds?).
I think it would be great if you add setting that will change this time.

**Comment by garbagemule** [comment]
Hiya @molor 

Could I get you to split this feature request up into two separate issues? I think they are wildly different in both implementation and intent, and I'd like to tackle them separately.

Thanks!

**Comment by molor** [comment]
Done
