### ISSUE TITLE
Mob Arena is uncancelling BlockExplodeEvents cancelled by LWC *outside* of arenas

### ISSUE THREAD

**Issue by Momshroom** [garbagemule/MobArena#717]
# Bug report

**Short description**

Our server has towny blocking explosions in most areas and LWC not allowing locks to be exploded.  Without MobArena this works beautifully.   When MobArena is installed we see the following:
If a respawn anchor is placed near a locked chest and exploded, the area around it will blow up as though towny is not blocking it and the chest will be exploded as though LWC does not stop it.   When there is no lock, towny blocks it appropriately. (whether or not there is a chest).   Removing MobArena returns us to the proper blocked behavior and EventDebugger shows MobArena setting the event to no longer be cancelled:[https://prnt.sc/26l1lxs]( https://prnt.sc/26l1lxs). This is NOT in an arena and not even in a world that has arenas and is reproducible everywhere we tried it.

**Reproduction steps**

1. Have LWC and MobArena (and possibly towny?) installed, and have LWC and towny set to block explosions
2. Place and charge a respawn anchor near a locked chest
3. Ground and chest explode

**Details**

No, stack trace, but https://prnt.sc/26l1lxs shows MobArena cancelling the event.

* **MobArena version**: 0.106
* **Server version**: paper 124 (1.18.1) 

**Additional info**

versions of towny and LWCX used:
towny 0.97.5.12 and another older version, lwc 2.2.7

**Comment by Maroon28** [comment]
Yep, someone reported this earlier and it was fixed in one of the dev builds! Check #704, if you want to get the newest build then you can grab one from [Github Actions ](https://github.com/garbagemule/MobArena/actions)

**Comment by Momshroom** [comment]
Thank you!
