### ISSUE TITLE
Thrown tridents can return to players that are not in the game

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#727]
# Bug report

**Short description**
Tridents can be duped by joining the game and using /ma l

**Reproduction steps**
1. Join an arena with /ma join
2. Hit a sign to pick a class that contains trident
3. Thrown it and, while it flying, type /ma leave
4. Trident will return to you
5. Repeat

**Details**

* **MobArena version**: https://github.com/garbagemule/MobArena/actions/runs/1946735906
* **Server version**: Paper 1.18.2

**Additional info**
Hope you can fix this ASAP, some of our players already duped tridents using this bug before some1 was reported it to me :c
Thanks!

**Comment by Nesseley** [comment]
This has already been reported: https://github.com/garbagemule/MobArena/issues/568

**Comment by molor** [comment]
> 28 Aug 2019

Oh so all I can do is just remove this class from arena :c

**Comment by Nesseley** [comment]
If you have any experience with developing feel free to fix it and make a pull request! :) I would, but I think this is out of my league. also chime in on the first issue :)
