### ISSUE TITLE
MobArena Player Exp Nerfs

### ISSUE THREAD

**Issue by kattnap671** [garbagemule/MobArena#739]
Heya, So, I was wondering if there is a way to kinda nerf the player's exp while in the Mobarena? It seems players are grinding the arena because exp is very easily obtainable. I could not any discussion on this topic. If we can just lower the amount of exp just a tad bit. That would be super awesome. Thanks for any help on this.

**Comment by Nesseley** [comment]
You need to follow the form that was in the box before you replaced it all with your text for the feature request to be valid. 

However, I don't think this is something MobArena will add in the near future, I'm thinking it belongs in the rework. 
If you want to limit exp, you can set exp to false in the arena settings, and instead add some bottles of enchanting in the rewards. That way you can limit how much exp they get.

**Comment by kattnap671** [comment]
Ahh perfect. That suonds good. I will give that go. Thank you again for everything. :)

**Comment by kattnap671** [comment]
This is like the fastest response ever! lmao. I'm used to waiting
 weeks and sometimes months for a response. lmao. Thanks again.

**Comment by Nesseley** [comment]
You are very welcome! 
If you need more support, we got a Discord where support is even faster! 🎉

**Comment by garbagemule** [comment]
@kattnap671 if you'd like to see something like this implemented in the future, please edit the first post to reflect the template that @Nesseley refers to and I'll stick the appropriate labels on it. Otherwise, feel free to close the issue.

**Comment by garbagemule** [comment]
Feel free to reopen if this is still relevant.
