### ISSUE TITLE
Item-Dupe Bug

### ISSUE THREAD

**Issue by Fnrs-Wlan** [garbagemule/MobArena#741]
# Bug report

**Short description**

Duplication of Items from the Classes using Inventory++

**Reproduction steps**
Kinda hard to do and dependet on the Server
Need Hack client with Inventory++ so you can keep items in your crafting slot
Different Ways of doing it

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Put the item you wanna duplicate into your crafting slot
4. Leave the mobarena with /ma leave
5. Get the items ( Needs other bugs to get back to the arena without being in the Mode )

or other way to do it using the Sit-Plugin

1. Sit on a slap
2. join the mobarena (at this point im in the mode and im still sitting on the slab)
3. select your class with /ma class *
4. Again item into crafting slot
5. leave mobarena with /ma leave
6. Still sitting on the slab with my normal inventory and the items from the class in the Crafting slot

Video showing the reproduction
https://youtu.be/ewRxJslgj0c

**Details**

Cant give many details cause i found this bug on a server im playing

**Comment by garbagemule** [comment]
Thank you for investing the time in this bug report, but behavior that requires a hacked client to pull off would fall under the umbrella of anti-cheat issues that we should _not_ attempt to fix. MobArena is not an anti-cheat plugin, doesn't aim to be one, and never will be one.

For future reference, MobArena does actually do [a bit more than it should](https://github.com/garbagemule/MobArena/blob/b76b0e67192548e40920589112eb822649c10656/src/main/java/com/garbagemule/MobArena/util/inventory/InventoryManager.java#L45-L61) to try to combat any "pulling items out" issues. From a quick browse through a small handful of other minigame plugins, they seem to handle it the same way or "less", adhering to the API the same way MobArena does.
