### ISSUE TITLE
Mobs disappearing randomly

### ISSUE THREAD

**Issue by Superalex0102** [garbagemule/MobArena#744]
# Bug report

**Short description**

Mobs randomly disappear in the background (approx 20-25 blocks away)

**Details**

[20:47:02 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version

**Comment by garbagemule** [comment]
MobArena removes monsters that leave the arena region, which is intended behavior. If they truly "disappear", then it's either your server software or a different plugin removing them.

It seems like there is a lot more troubleshooting and experimenting to do here before we do any sort of "bug fixing", and for that I'll refer to the Discord server. Feel free to reopen if this is actually a bug in MobArena.
