### ISSUE TITLE
Improve the Spectator feature

### ISSUE THREAD

**Issue by Superalex0102** [garbagemule/MobArena#745]
# Feature request

**Short description**

It's a really simple feature that's need to be added, nothing special, add a configuration option (or by default) so spectators are invisible.

**Comment by garbagemule** [comment]
I'm not sure why spectators would have to be invisible or what value that would bring to the plugin. They're already tucked away in a confined area (at least they should be). So why do you want to make them invisible?

**Comment by Superalex0102** [comment]
In every minigame the spectators are invisible so they don't bother other players or confuse them, my arena map is pretty bad to be watched from the top (and to be honest everyone wants to spectate closer and not 30-40 blocks above.

**Comment by garbagemule** [comment]
Okay, it seems like we can consolidate this into #411 which already addresses the idea of using the spectator game mode. Feel free to contribute any additional information on that issue. It sounds like you have a great deal of experience with other minigames that successfully implement the concept, so perhaps you can share which ones and how they work.
