### ISSUE TITLE
ender chest problem

### ISSUE THREAD

**Issue by sorandno** [garbagemule/MobArena#749]
**Short description**
I want the ender chest to be unusable

Bring in a workbench, eye of ender, and obsidian to craft and easily duplicate items.

Easily duplicate items with MyItems

**Implementation details**
I want the ender chest to be unusable

**Additional info**
test server version : 1.19.2

MobArena version : 0.107

**Comment by prototype464** [comment]
Just use WorldGuard to restrict players' ability to open ender chests.
