### ISSUE TITLE
Allow adding a player name to the /ma join command

### ISSUE THREAD

**Issue by Josh-65** [garbagemule/MobArena#752]
# Feature request

**Short description**

It currently only has arena as an optional. `/ma join <arena> <player>` would allow command blocks to work with this and in the console if needed. 

**Implementation details**

A permission to allow a moderator in game to run this command would be need like `mobarena.join.other`

**Comment by garbagemule** [comment]
I think this is a duplicate of #594, so I'm gonna close the issue for now, but please feel free to reopen it if the other issue doesn't cover this use case. From what I understand this is already doable with a `sudo` style plugin.
