### ISSUE TITLE
Boss Killing in One Shot

### ISSUE THREAD

**Issue by Drizzt11** [garbagemule/MobArena#755]
So the boss is one shotting my players. Here is the config on the boss. I think it has to be the Throw-Nearby ability because I received a death notification saying I died from a high place escaping a zombie pigman.

        boss1:
          type: boss
          wave: 10
          monster: zombie-pigmen
          health: low
          abilities: arrows, root-target, throw-nearby

**Comment by garbagemule** [comment]
Let's track this on #757 since it follows the bug report template and contains a bit more relevant detail in the title :)
