### ISSUE TITLE
Make the spigot health error spit itself out in chat and not just console

### ISSUE THREAD

**Issue by LucyValeheart** [garbagemule/MobArena#764]
# Feature request

**Short description**
Theres a spigot setting that makes bosses that would have over x amount of hp spawn with the default mob hp (zombie 20, spider 16, etc). when the issue occurs, mobarena currently spits out an error detailing what happened and how to fix it into console.
We should make it spit the error out in chat, too- ideally to both admins/ops and players in the arena fighting the boss.

**Implementation details**
I'm not sure the complexity of making it spit the message to just players playing the arena, so if its a little difficult, for now focus should be getting the message in chat to admins. if its easy, though, great, slap it in there.

**Comment by Scot-Survivor** [comment]
I do agree this should be permission based however. mobarena.error or something. 

It looks mighty unprofessional to standard users if you have errors spat out in chat. 

Similarly the principle of least privilege comes into play. "Does this group need to see this info? No. Then refuse it.". Even if something seems harmless, principle of least privilege should apply.
