### ISSUE TITLE
Sign problem 1.20.1

### ISSUE THREAD

**Issue by DexterSK** [garbagemule/MobArena#765]
# Bug report

**Short description**

When you right click on arena sign it will open SignGUI

**Reproduction steps**

1. Right click on sign

**Details**

* **MobArena version**: 0.107
* **Server version**: git-Purpur-1995 (MC: 1.20.1)
* **Stacktrace** (if applicable): 

**Additional info**

**Comment by DexterSK** [comment]
I think it was problem with other plugin. sorry

**Comment by DexterSK** [comment]
Ok so issue is still there, it worked one time but now again doesn't. When i right click sign it will open edit sign gui and console will say player xxx tried to edit non editable sign.

**Comment by Bobcat00** [comment]
Is your arena protected by any other plugins, like WorldGuard or GriefPrevention? That seems to be a CraftBukkit message for the cases of the sign being waxed or the wrong player is editing it (don't really understand all this):
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/world/level/block/entity/TileEntitySign.patch#50

I have a branch that stops the dialog from being opened, but it may not be the perfect solution:
https://github.com/Bobcat00/MobArena/commit/2cbb4909fb51b06e48b9018c79787997c91afd39?w=1

**Comment by DexterSK** [comment]
yup i have wg region

**Comment by DexterSK** [comment]
do i need to remove region?

**Comment by veteranmina** [comment]
Haven't really looked, but is this possibly due to the new 1.20 feature of double-sided signs?

**Comment by BobbyTowers** [comment]
I only get this on the second arena. The first one works fine.

**Comment by garbagemule** [comment]
@DexterSK @BobbyTowers @veteranmina I've got a fix for this issue ready if anyone wants to try it out. Let me know if you prefer to build it yourself (branch `765-sign-edit`) or if you'd like me to send you a build on Discord.

**Comment by BobbyTowers** [comment]
I would like a build, what's your discord?

**Comment by garbagemule** [comment]
I'll drop one in the #test-builds channel on the MobArena Discord.

**Comment by Nesseley** [comment]
[For the lazy ones](https://discord.com/invite/5tnwQvC)
