### ISSUE TITLE
Make pets killable and allow starting xp option

### ISSUE THREAD

**Issue by BlankRedemption** [garbagemule/MobArena#767]
# Feature request

1. Perhaps allowing a toggle option for pets to be invincible would be a fun way to use upgrade/supply wave. 
2. Also, using a starting XP system would allow for an enchant room or plugins for custom enchants to be used sooner rather than later (I use Zenchantments).
3. Furthermore, I was hoping to add in a boss spawnpoint
4. Finally, adding a way to allow players to spawn mobs (iron golem, snow golem etc)

-----------------------------------------------------------------------------------------------------------------------------------------

- Pets invincibility

arenas:
  ARENA_NAME:
    settings:
      prefix: ''
      --invincible-pet: [true/false] DEFAULT IS TRUE--
      world: WORLD-NAME
      enabled: true
      protect: true
      ...
      ...

-----------------------------------------------------------------------------------------------------------------------------------------
- Starting XP

arenas:
  ARENA_NAME:
    settings:
      prefix: ''
      --invincible-pet: [true/false] DEFAULT IS TRUE--
      --starting-xp: [30,1395] (LEVEL,EXPERIENCE) (LEVEL OR EXPERIENCE WHICH EVER IS EASIER TO CODE) DEFAULT IS 0--
      world: WORLD-NAME
      enabled: true
      protect: true
      ...
      ...

-----------------------------------------------------------------------------------------------------------------------------------------
 - Boss Spawnpoints
 
Making another item in the /MA SETUP [ARENA_NAME] to have a specific spot for spawning bosses

-----------------------------------------------------------------------------------------------------------------------------------------
- Player Created Mobs

Unfortunately **I can't explain or understand** how this would be possible but building a golem or spawning one in via a command block would be a nice implementation. 
Making this per arena apposed to global allows for greater personalization for the user that shouldn't (in theory) affect other arenas

-----------------------------------------------------------------------------------------------------------------------------------------

**Additional info**
I have no idea how to code for java or what your files might look but i've been using your plugin on and off for i don't even know how long and always thought about this kind of stuff. Thank you for your time!

The only issue i see is skeletons dropping bones and giving a player 15 wolves a wave.

**Comment by Nesseley** [comment]
All of these should be reposted as it's own feature request :)

I also think boss spawnpoint is already suggested.
