### ISSUE TITLE
Leaderboard Placeholder

### ISSUE THREAD

**Issue by PabloKateee** [garbagemule/MobArena#782]
Their plugin is absolutely awesome, but with the placeholders we still really need that 1 update from them :D 
A best list placeholder, where the players and rounds are in it I would give you an example:

%mobarena_round_<position>% 
%mobarena_wave_<position>% 
%mobarena_player_<position>%
%mobarena_mobkills_<position>%

Example:

Mobarena Stats for all Players on this Server:

1. Player[A] Highsest Round 544 Mobkills: 23222
2. Player[B] Highsest Round 244 Mobkills: 20222
3. Player[C] Highsest Round 211 Mobkills: 18222
e.g

The Mobarena is the most capable plugin I have ever seen. But the leaderboards placeholders are definitely missing, otherwise the players have no motivation to play high rounds because they don't know who is in first place or who is the best player in the mobarena. Because you can't make it visible to the players to show which player has survived how many rounds.
If they provide this update, it will perfect the system 100%, as it is a factor for servers with active players to be the best and show it :D

Of course, after this update there will be something for the coffee fund from me as a thank you :D I would be very happy about positive feedback from you

**Comment by PabloKateee** [comment]
![image](https://github.com/garbagemule/MobArena/assets/77749892/cb6d31fa-14a6-4ba7-8bb6-0d321bd51174)

Like This 
But only that you can see which player has overleveled how many rounds, and that you could maybe optionally add the mobkills :D

**Comment by garbagemule** [comment]
Closing this, as it doesn't have anything to do with the core plugin. Feel free to contribute on the relevant extension plugin issues:

- https://github.com/mobarena/MobArenaPlaceholders/issues/11
- https://github.com/mobarena/MobArenaStats/issues/20
