### ISSUE TITLE
configuration => Wolves that spawn only??

### ISSUE THREAD

**Issue by centerworld2023** [garbagemule/MobArena#788]
Hello, 

I’m writing here to ask for help. 
A few days ago we had the plugins, and I’m wondering about some points that I can’t solve. 

Currently when the game is launched, only wolves popent, no other aggressive mob spawn for an X reason. 

I have tested several times since yesterday, in vain. 

Would anyone have a solution including the "why" only wolves spawn? 

Thanks 

Regards

**Comment by garbagemule** [comment]
It's WorldGuard.

Please use Discord if you need further assistance.

**Comment by centerworld2023** [comment]
Can you send me your discord? I didn’t find it while searching on Spigot. 

Thank you.
