### ISSUE TITLE
Block people to use the command "/Ma class xxx"

### ISSUE THREAD

**Issue by Blastrax** [garbagemule/MobArena#794]
Hi, i dont know if its possible pr nope, if it is i didn't find it ...

I've creater many classes, arena etc, i've put signs to choose classes, and every arena have her own classes beacuse its not the same difficulty on each arena, so an ultra hard arena can have a full netherite stuff full enchant, when an easy arena can only have a stone sword
The signs are perfect to limite the class i want  per arena, but the problem is everyon can use the command /ma class xxx, and so people can cheat using classes they're normally not able to, like they use the full netherite on the easy arena
I try to block the command to non admin people but i can't or didn't find how to do
If you have a solution i wanna take it :)
Thanks for your help and for this incredible plugin

**Comment by garbagemule** [comment]
You can use the class limits section of the config-file to set how many of each class a session can have. Set the classes you don't want to 0 and that should be it :)

Class limits may not be documented. I'll see if I can sort that out.
